# CCL

[[secrets]]
name = "Latin America - Invitados - Café con Leche"
secret = "sa431"

[[secrets]]
name = "Brasil - Café com leite"
secret = "542ao"

[[secrets]]
name = "Mexico - Invitados - Café con Leche"
secret = "43hht"

[[secrets]]
name = "Caribbean Finals"
secret = "inegc"

[[secrets]]
name = "Central America Finals"
secret = "ue234"

[[secrets]]
name = "Mexico Finals"
secret = "kx98"

[[secrets]]
name = "South America - North Finals"
secret = "uno89"

[[secrets]]
name = "South America - South Finals"
secret = "x9ozt"

[[secrets]]
name = "Brazilian Finals"
secret = "19xkot"
