[package]
name = "service"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
tokio.workspace = true
zip.workspace = true
html-escape.workspace = true
parking_lot.workspace = true
reqwest.workspace = true
thiserror.workspace = true
metrics.workspace = true
tracing.workspace = true
serde.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true

data.workspace = true
