services:
  printurls:
    image: wuerges/animeitor-v2:latest
    entrypoint: "/printurls"
    command: "--prefix ${PREFIX} --sedes ${SEDES}: --secret ${SECRET}"
    volumes:
      - ./config:/config
    build:
      context: .

  animeitor-v2:
    image: wuerges/animeitor-v2:latest
    command: "-v /photos:photos -v /dist: --sedes ${SEDES}: --secret ${SECRET} ${BOCA_URL}"
    volumes:
      - ./tests:/tests
      - ./config:/config
      # place your team photos inside of ./server/photos
      - ./server/photos:/photos
      # place your team sounds inside of ./server/sounds
      - ./server/sounds:/sounds
      # the ./client-v2/static/user-styles.css can be edited, and it will
      # overwrite the styles from the app
      - ./client-v2/static/user-styles.css:/dist/user-styles.css
    ports:
      - ${PUBLIC_PORT}:8000

    environment:
      - RUST_LOG=debug

    build:
      context: .
