version: "3.7"
services:
  animeitor:
    image: wuerges/animeitor:latest
    command: "--sedes ${SEDES} --secret ${SECRET} ${BOCA_URL} --port 8000"
    volumes:
      - ./tests:/tests
      - ./config:/config

    build:
      context: server
      args:
        - DOCKER_BUILDKIT=1

  printurls:
    image: wuerges/animeitor:latest
    command: "--sedes ${SEDES} --secret ${SECRET} --prefix http://localhost:9000"
    volumes:
      - ./config:/config
    entrypoint: /printurls

    build:
      context: server
      args:
        - DOCKER_BUILDKIT=1

  animeitor-client:
    image: wuerges/animeitor-client:latest
    ports:
      - 9000:80
    volumes:
      - ./server/photos:/usr/share/nginx/html/static/assets/teams:ro
      - ./client-nginx.conf:/etc/nginx/conf.d/default.conf:ro

    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        - REMOVE_CCL=0
        - URL_PREFIX=http://localhost:9000/api
        - PHOTO_PREFIX=http://localhost:9000/static/assets/teams
