version: "3.7"
services:
  animeitor:
    image: wuerges/animeitor:latest
    command: "--sedes ${SEDES} --secret ${SECRET} ${BOCA_URL} --port 8000"
    ports:
      - 8000:8000
    volumes:
      - ./tests:/tests
      - ./config:/config

    build:
      context: server
      args:
        - DOCKER_BUILDKIT=1

  printurls:
    image: wuerges/animeitor:latest
    command: "--sedes ${SEDES} --secret ${SECRET} --prefix http://localhost:9000"
    volumes:
      - ./config:/config
    entrypoint: /printurls

    build:
      context: server
      args:
        - DOCKER_BUILDKIT=1

  animeitor-client:
    image: wuerges/animeitor-client:latest
    ports:
      - 9000:80
    volumes:
      - /server/photos:/usr/share/nginx/photos

    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        - URL_PREFIX=http://localhost:8000
