services:
  printurls:
    # same image as animeitor below, which is the service that builds it
    image: wuerges/animeitor:latest
    entrypoint: "/printurls"
    command: "--server ${SERVER_URL} --token ${INTERNAL_TOKEN} --prefix ${PREFIX}"
    environment:
      - RUST_LOG=info


  feeder:
    # polls BOCA and publishes event + runs into the internal API
    image: wuerges/animeitor:latest
    entrypoint: "/update_contest_state"
    command: "-t ${INTERNAL_TOKEN} -i ${BOCA_URL} -s http://animeitor:8000 --event default"
    volumes:
      - ./tests:/tests
    environment:
      - RUST_LOG=info
    depends_on:
      - animeitor


  animeitor:
    image: wuerges/animeitor:latest
    command: "-v /photos:photos -v /sounds:sounds -v /dist: -v /dist:animeitor -t ${INTERNAL_TOKEN}"
    volumes:
      - ./tests:/tests
      # place your team photos inside of ./server/photos
      - ./server/photos:/photos
      # place your team sounds inside of ./server/sounds
      - ./server/sounds:/sounds
      # the ./client-v2/static/user-styles.css can be edited, and it will
      # overwrite the styles from the app
      - ./client-v2/static/user-styles.css:/dist/user-styles.css
    ports:
      - ${PUBLIC_PORT}:8000

    environment:
      - RUST_LOG=info

    build:
      context: .
      platforms:
      - linux/amd64/v2
