version: "3.7"
services:
  animeitor:
    image: wuerges/animeitor:latest
    # image: wuerges/animeitor:0.5.0
    command: "--config $SEDES --secret $SECRET $BOCA_URL --port 8000"
    ports: 
      - 8000:8000
    volumes:
      - ./tests:/tests
      - ./config:/config

    build: 
      context: .
      args:
        - DOCKER_BUILDKIT=1

  animeitor-client:
    image: wuerges/animeitor-client:latest
    # image: wuerges/animeitor-assets:0.5.0
    ports: 
      - 8080:80
    volumes:
      - ./photos:/usr/share/nginx/photos

    build: 
      context: .
      dockerfile: client.Dockerfile
      args:
        - URL_PREFIX=http://localhost:8000
