version: "3.7"
services:
  animeitor:
    image: wuerges/animeitor:0.5.0
    command: "--config $SEDES --secret $SECRET $BOCA_URL --port $HTTP_PORT --public $HTTP_PORT"
    ports: 
      - $HTTP_PORT:$HTTP_PORT
    volumes:
      - ./photos:/photos
      - ./tests:/tests
      - ./config:/config


