services:
  animeitor-v2:
    image: wuerges/animeitor-v2:latest
    command: "-v /photos:photos -v /dist: --sedes ${SEDES}: --secret ${SECRET} ${BOCA_URL}"
    volumes:
      - ./tests:/tests
      - ./config:/config
      - ./server/photos:/photos
    ports:
      - 8000:8000

    environment:
      - RUST_LOG=debug

    build:
      context: .
