apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: animeitor
  namespace: maratona-animeitor
spec:
  template:
    spec:
      containerConcurrency: 1000
      containers:
      - image: us-central1-docker.pkg.dev/maratona-animeitor/repo/animeitor
        args:
          - "--port=8080"
          - "--volume=/photos:photos"
          - "--volume=/sounds:sounds"
          - "--volume=/dist:"
          - "--secret=/config/regional_2024/Secrets.toml"
          - "--sedes=/config/regional_2024/Brasil.toml:"
          - "/tests/inputs/webcast-2023-1a-fase-final-prova.zip"
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/target: "1000"
