[package]
name = "cli"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
toml.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
clap.workspace = true
color-eyre.workspace = true
url.workspace = true
rand.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
openssl-sys = { optional = true, version = "0.9" }
reqwest.workspace = true

data.workspace = true
client-model.workspace = true
service.workspace = true
sentry.workspace = true

[dev-dependencies]
rstest.workspace = true

[features]
slow_tests = []
vendored = ["openssl-sys/vendored"]
