[[secrets]]
name = "Bolivia"
secret = "x0aoihx123egt"

[[secrets]]
name = "Brasil"
secret = "x9z5xtn1t23h8ed4q"

[[secrets]]
name = "Centro America"
secret = "pfytqxxqqeuz11"

[[secrets]]
name = "Mexico"
secret = "xuah54zz2ntho1"

[[secrets]]
name = "CCL"
secret = "x9utizx89anoest"

[[secrets]]
name = "Bolivia CCL"
secret = "902dan9ozanot"

[[secrets]]
name = "Brasil CCL"
secret = "584aiaoeuaoezdt"

[[secrets]]
name = "Centro America CCL"
secret = "345z892varoetqj"

[[secrets]]
name = "Mexico CCL"
secret = "z1va5o4e1taj"
