[[secrets]]
name = "Brasil"
secret = "ni8euu13"

[[secrets]]
name = "Mexico"
secret = "i8u9eiz"

[[secrets]]
name = "Bolivia"
secret = "54as423"

[[secrets]]
name = "Centro America"
secret = "1zj0x89"

[[secrets]]
name = "CCL"
secret = "i425disa"

[[secrets]]
name = "Brasil CCL"
secret = "auv234"

[[secrets]]
name = "Bolivia CCL"
secret = "7cveh8"

[[secrets]]
name = "Centro America CCL"
secret = "345zqj"

[[secrets]]
name = "Supersede MS"
secret = "1b8aoeuSupersede MS"

[[secrets]]
name = "Supersede MT"
secret = "1b8aoeuSupersede MT"

[[secrets]]
name = "Supersede NE"
secret = "1b8aoeuSupersede NE"

[[secrets]]
name = "Supersede RN"
secret = "1b8aoeuSupersede RN"

[[secrets]]
name = "Supersede Norte"
secret = "1b8aoeuSupersede Norte"

[[secrets]]
name = "Supersede MG"
secret = "1b8aoeuSupersede MG"

[[secrets]]
name = "Supersede SE"
secret = "1b8aoeuSupersede SE"

[[secrets]]
name = "Supersede Sul"
secret = "1b8aoeuSupersede Sul"

[[secrets]]
name = "ES, Vitoria"
secret = "1b8aoeuES, Vitoria"

[[secrets]]
name = "PB, Campina Grande"
secret = "1b8aoeuPB, Campina Grande"

[[secrets]]
name = "BA, Juazeiro"
secret = "1b8aoeuBA, Juazeiro"

[[secrets]]
name = "CE, Fortaleza"
secret = "1b8aoeuCE, Fortaleza"

[[secrets]]
name = "CE, Juazeiro do Norte"
secret = "1b8aoeuCE, Juazeiro do Norte"

[[secrets]]
name = "CE, Quixada"
secret = "1b8aoeuCE, Quixada"

[[secrets]]
name = "GO, Goiania"
secret = "1b8aoeuGO, Goiania"

[[secrets]]
name = "MA, Balsas"
secret = "1b8aoeuMA, Balsas"

[[secrets]]
name = "MG, Belo Horizonte"
secret = "1b8aoeuMG, Belo Horizonte"

[[secrets]]
name = "MG, Montes Claros"
secret = "1b8aoeuMG, Montes Claros"

[[secrets]]
name = "MS, Campo Grande"
secret = "1b8aoeuMS, Campo Grande"

[[secrets]]
name = "SP, Taubate"
secret = "1b8aoeuSP, Taubate"

[[secrets]]
name = "PI, Teresina"
secret = "1b8aoeuPI, Teresina"

[[secrets]]
name = "RJ, Rio de Janeiro"
secret = "1b8aoeuRJ, Rio de Janeiro"

[[secrets]]
name = "RN, Pau dos Ferros"
secret = "1b8aoeuRN, Pau dos Ferros"

[[secrets]]
name = "SP, Sao Paulo"
secret = "1b8aoeuSP, Sao Paulo"

[[secrets]]
name = "RO, Porto Velho"
secret = "1b8aoeuRO, Porto Velho"

[[secrets]]
name = "MG, Uberlandia"
secret = "1b8aoeuMG, Uberlandia"

[[secrets]]
name = "DF, Brasilia"
secret = "1b8aoeuDF, Brasilia"

[[secrets]]
name = "MG, Sao Joao de"
secret = "1b8aoeuMG, Sao Joao de"

[[secrets]]
name = "PE, Olinda"
secret = "1b8aoeuPE, Olinda"

[[secrets]]
name = "PR, Campo Mourao"
secret = "1b8aoeuPR, Campo Mourao"

[[secrets]]
name = "RS, Porto Alegre"
secret = "1b8aoeuRS, Porto Alegre"

[[secrets]]
name = "SC, Florianopolis"
secret = "1b8aoeuSC, Florianopolis"

[[secrets]]
name = "SE, Sao Cristovao"
secret = "1b8aoeuSE, Sao Cristovao"

[[secrets]]
name = "SP, Sorocaba"
secret = "1b8aoeuSP, Sorocaba"

[[secrets]]
name = "MT, Cuiaba"
secret = "1b8aoeuMT, Cuiaba"

[[secrets]]
name = "MG, Muzambinho"
secret = "1b8aoeuMG, Muzambinho"

[[secrets]]
name = "MG, Patrocinio"
secret = "1b8aoeuMG, Patrocinio"

[[secrets]]
name = "PA, Belem"
secret = "1b8aoeuPA, Belem"

[[secrets]]
name = "PA, Maraba"
secret = "1b8aoeuPA, Maraba"

[[secrets]]
name = "RS, Passo Fundo"
secret = "1b8aoeuRS, Passo Fundo"

[[secrets]]
name = "SP, Marilia"
secret = "1b8aoeuSP, Marilia"

[[secrets]]
name = "SP, Santos"
secret = "1b8aoeuSP, Santos"

[[secrets]]
name = "PI, Parnaiba"
secret = "1b8aoeuPI, Parnaiba"

[[secrets]]
name = "MG, Vicosa"
secret = "1b8aoeuMG, Vicosa"

[[secrets]]
name = "BA, Salvador"
secret = "1b8aoeuBA, Salvador"

[[secrets]]
name = "AC, Rio Branco"
secret = "1b8aoeuAC, Rio Branco"

[[secrets]]
name = "AL, Maceio"
secret = "1b8aoeuAL, Maceio"

[[secrets]]
name = "MA, Sao Luis"
secret = "1b8aoeuMA, Sao Luis"

[[secrets]]
name = "AM, Manaus"
secret = "1b8aoeuAM, Manaus"

[[secrets]]
name = "RN, Natal"
secret = "1b8aoeuRN, Natal"

[[secrets]]
name = "MS, Dourados"
secret = "1b8aoeuMS, Dourados"

[[secrets]]
name = "MT, Sinop"
secret = "1b8aoeuMT, Sinop"

[[secrets]]
name = "TO, Palmas"
secret = "1b8aoeuTO, Palmas"

[[secrets]]
name = "SC, Joinville"
secret = "1b8aoeuSC, Joinville"

[[secrets]]
name = "MT, Alto Araguaia"
secret = "1b8aoeuMT, Alto Araguaia"

[[secrets]]
name = "PA, Oriximina"
secret = "1b8aoeuPA, Oriximina"

[[secrets]]
name = "SP, Sao Carlos"
secret = "1b8aoeuSP, Sao Carlos"

[[secrets]]
name = "SE, Sao Cristovao"
secret = "1b8aoeuSE, Sao Cristovao"
