[titulo]
name = "Latin America"
codes = ["team"]

[[sedes]]
name = "Latin America"
codes = [""]

[[sedes]]
codes = ["teambrbr"]
name = "Brazilian Finals"

[[sedes]]
codes = ["teamcacr"]
name = "Costa Rica Site"

[[sedes]]
codes = ["teamcaes"]
name = "El Salvador Site"

[[sedes]]
codes = ["teamcagt"]
name = "Guatemala Site"

[[sedes]]
codes = ["teamcbab"]
name = "Antigua & Barbuda (Regional Site)"

[[sedes]]
codes = ["teamcbcu"]
name = "Cuba (Regional Site)"

[[sedes]]
codes = ["teamcbdr"]
name = "Dominican Republic (Regional Site)"

[[sedes]]
codes = ["teamcbpr"]
name = "Puerto Rico (Regional Site)"

[[sedes]]
codes = ["teamcbtt"]
name = "Trinidad & Tobago (Regional Site)"

[[sedes]]
codes = ["teammxmx"]
name = "Mexico Site"

[[sedes]]
codes = ["teamnoco"]
name = "Colombia"

[[sedes]]
codes = ["teamnovz"]
name = "Venezuela"

[[sedes]]
codes = ["teamsoar"]
name = "Argentina"

[[sedes]]
codes = ["teamsobo"]
name = "Bolivia"

[[sedes]]
codes = ["teamsoch"]
name = "Chile"

[[sedes]]
codes = ["teamsopa", "teamsope"]
name = "Peru"
