titulo = "Contest Exemplo"

[[sedes]]
# Nome da sede, usado no basic_secret.toml 
name = "Sede Exemplo"
# Estilo da sede, para customizar o CSS
style = "sede_exemplo"
premiacao = false
vagas = 5
# Substring para casar times dessa sede
codes = ["team"]
ouro = 4
prata = 8
bronze = 12

