salt = "salt"

[[secrets]]
name = "North"
secret = "North"

[[secrets]]
name = "Venezuela"
secret = "Venezuela"

[[secrets]]
name = "Colombia"
secret = "Colombia"

[[secrets]]
name = "South"
secret = "South"

[[secrets]]
name = "Argentina"
secret = "Argentina"

[[secrets]]
name = "Bolivia"
secret = "Bolivia"

[[secrets]]
name = "Chile"
secret = "Chile"

[[secrets]]
name = "Peru"
secret = "Peru"

[[secrets]]
name = "Brasil"
secret = "Brasil"

[[secrets]]
name = "Mexico"
secret = "Mexico"

[[secrets]]
name = "Central America"
secret = "America"

[[secrets]]
name = "El Salvador"
secret = "Salvador"

[[secrets]]
name = "Costa Rica"
secret = "Rica"

[[secrets]]
name = "Caribe"
secret = "Caribe"

[[secrets]]
name = "Cuba"
secret = "Cuba"

[[secrets]]
name = "Republica Dominicana"
secret = "Dominicana"

[[secrets]]
name = "Puerto Rico"
secret = "Rico"

[[secrets]]
name = "Latin America"
secret = "America"
