[workspace]
members = ["server", "data", "cli", "service"]
resolver = "2"

[workspace.package]
version = "0.7.0"
edition = "2021"
authors = ["Emilio Wuerges <wuerges@gmail.com>"]

[workspace.dependencies]
autometrics = { version = "0.2.4", features = [
    "prometheus-exporter",
    "metrics",
] }
aho-corasick = "0.7"
clap = "2"
color-eyre = "0.6"
futures = "0.3"
html-escape = "0.2"
hyper = { version = "0.14", features = ["client", "http2"] }
hyper-tls = "0.5"
itertools = "0.10"
metrics = "0.20"
metrics-prometheus = "0.3"
openssl = { version = "0.10", features = ["vendored"] }
parking_lot = "0.12"
prometheus = { version = "0.13", features = ["process"] }
rand = "0.8"
rust-embed = "6.6"
thiserror = "1.0"
toml = "0.7"
sentry = "0.30"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.27", features = ["full"] }
url = "2"
warp = "0.3"
zip = "0.6"

