titulo = "Programadores da America"

[[sedes]]
# Nome da sede, usado no basic_secret.toml
name = "America Latina"
# Substring para casar times dessa sede
# Somente times que contem esse substring pertencerao a sede
# codes = ["team"]
codes = [""]
ouro = 4
prata = 8
bronze = 12
