[titulo]
name = "Programadores da América"
codes = [""]

[[sedes]]
name = "América Latina"
codes = [""]
ouro = 4
prata = 8
bronze = 12

[[sedes]]
name = "North"
codes = ["teamno"]
ouro = 1
prata = 2
bronze = 3

[[sedes]]
name = "South"
codes = ["teamso"]
ouro = 1
prata = 2
bronze = 3

[[sedes]]
name = "América Central"
codes = ["teamca"]
ouro = 1
prata = 2
bronze = 3

[[sedes]]
name = "Caribe"
codes = ["teamcb"]
ouro = 1
prata = 2
bronze = 3

[[sedes]]
name = "Brasil"
codes = ["teambr"]
ouro = 1
prata = 2
bronze = 3

[[sedes]]
name = "México"
codes = ["teammx"]
ouro = 1
prata = 2
bronze = 3
