[[escolas]]
code="cefet-mg"
logo="cefet-mg.png"
name="cefet-mg"

[[escolas]]
code="cefet-rj"
logo="cefet-rj.png"
name="cefet-rj"

[[escolas]]
code="fatec-sorocaba"
logo="fatec-sorocaba.jpg"
name="fatec-sorocaba"

[[escolas]]
code="ifceara"
logo="ifceara.png"
name="ifceara"

[[escolas]]
code="ifpb-joaopessoa"
logo="ifpb-joaopessoa.png"
name="ifpb-joaopessoa"

[[escolas]]
code="ifsp"
logo="ifsp.png"
name="ifsp"

[[escolas]]
code="ifsuldeminas"
logo="ifsuldeminas.png"
name="ifsuldeminas"

[[escolas]]
code="ime"
logo="ime.jpg"
name="ime"

[[escolas]]
code="inatel"
logo="inatel.jpg"
name="inatel"

[[escolas]]
code="ita"
logo="ita.png"
name="ita"

[[escolas]]
code="puc-goias"
logo="puc-goias.jpg"
name="puc-goias"

[[escolas]]
code="puc-rio"
logo="puc-rio.jpg"
name="puc-rio"

[[escolas]]
code="udesc"
logo="udesc.png"
name="udesc"

[[escolas]]
code="uea"
logo="uea.png"
name="uea"

[[escolas]]
code="uece"
logo="uece.png"
name="uece"

[[escolas]]
code="uefs"
logo="uefs.jpg"
name="uefs"

[[escolas]]
code="uesb"
logo="uesb.jpg"
name="uesb"

[[escolas]]
code="ufabc"
logo="ufabc.png"
name="ufabc"

[[escolas]]
code="ufac"
logo="ufac.png"
name="ufac"

[[escolas]]
code="ufal-arapiraca"
logo="ufal-arapiraca.png"
name="ufal-arapiraca"

[[escolas]]
code="ufal"
logo="ufal.png"
name="ufal"

[[escolas]]
code="ufam"
logo="ufam.jpg"
name="ufam"

[[escolas]]
code="ufba"
logo="ufba.jpg"
name="ufba"

[[escolas]]
code="ufce"
logo="ufce.jpg"
name="ufce"

[[escolas]]
code="ufce-quixada"
logo="ufce-quixada.png"
name="ufce-quixada"

[[escolas]]
code="ufcg"
logo="ufcg.png"
name="ufcg"

[[escolas]]
code="ufes"
logo="ufes.png"
name="ufes"

[[escolas]]
code="ufg"
logo="ufg.png"
name="ufg"

[[escolas]]
code="ufma"
logo="ufma.jpg"
name="ufma"

[[escolas]]
code="ufmg"
logo="ufmg.png"
name="ufmg"

[[escolas]]
code="ufms"
logo="ufms.png"
name="ufms"

[[escolas]]
code="ufmt"
logo="ufmt.jpg"
name="ufmt"

[[escolas]]
code="ufpa"
logo="ufpa.png"
name="ufpa"

[[escolas]]
code="ufpe"
logo="ufpe.jpg"
name="ufpe"

[[escolas]]
code="ufpi"
logo="ufpi.jpg"
name="ufpi"

[[escolas]]
code="ufpr"
logo="ufpr.jpg"
name="ufpr"

[[escolas]]
code="ufrgs"
logo="ufrgs.png"
name="ufrgs"

[[escolas]]
code="ufrj"
logo="ufrj.jpg"
name="ufrj"

[[escolas]]
code="ufrn"
logo="ufrn.png"
name="ufrn"

[[escolas]]
code="ufrr"
logo="ufrr.png"
name="ufrr"

[[escolas]]
code="ufscar"
logo="ufscar.png"
name="ufscar"

[[escolas]]
code="ufsc"
logo="ufsc.png"
name="ufsc"

[[escolas]]
code="ufs"
logo="ufs.png"
name="ufs"

[[escolas]]
code="ufu"
logo="ufu.png"
name="ufu"

[[escolas]]
code="ufv-florestal"
logo="ufv-florestal.png"
name="ufv-florestal"

[[escolas]]
code="ufv"
logo="ufv.jpg"
name="ufv"

[[escolas]]
code="unb-gama"
logo="unb-gama.jpg"
name="unb-gama"

[[escolas]]
code="unb"
logo="unb.png"
name="unb"

[[escolas]]
code="unesc"
logo="unesc.jpg"
name="unesc"

[[escolas]]
code="unesp"
logo="unesp.png"
name="unesp"

[[escolas]]
code="unicamp"
logo="unicamp.png"
name="unicamp"

[[escolas]]
code="unifap"
logo="unifap.png"
name="unifap"

[[escolas]]
code="unifei"
logo="unifei.png"
name="unifei"

[[escolas]]
code="unir"
logo="unir.png"
name="unir"

[[escolas]]
code="univem"
logo="univem.jpg"
name="univem"

[[escolas]]
code="unoeste"
logo="unoeste.png"
name="unoeste"

[[escolas]]
code="usp"
logo="usp.png"
name="usp"

[[escolas]]
code="usp-sc"
logo="usp-sc.png"
name="usp-sc"

[[escolas]]
code="utfpr"
logo="utfpr.png"
name="utfpr"