titulo = "ICPC Latin America Regional Contest"

[[sedes]]
name = "Latin America"
contest = "Latin America"
premiacao = false
codes = ["team"]
ouro = 3
prata = 6
bronze = 10

# NORTH
#   Colombia  noco
#   Venezuela  novz
[[sedes]]
name = "North"
contest = "North"
premiacao = false
codes = ["teamno"]

[[sedes]]
name = "Colombia"
contest = "North"
premiacao = false
codes = ["teamnoco"]

[[sedes]]
name = "Venezuela"
contest = "North"
premiacao = false
codes = ["teamnovz"]

# SOUTH
#   Argentina  soar
#   Bolivia  sobo
#   Chile  soch
#   Peru  sope
[[sedes]]
name = "South"
contest = "South"
premiacao = false
codes = ["teamso"]

[[sedes]]
name = "Argentina"
contest = "South"
premiacao = false
codes = ["teamsoar"]

[[sedes]]
name = "Bolivia"
contest = "South"
premiacao = false
codes = ["teamsobo"]

[[sedes]]
name = "Chile"
contest = "South"
premiacao = false
codes = ["teamsoch"]

[[sedes]]
name = "Peru"
contest = "South"
premiacao = false
codes = ["teamsope"]


# BRASIL
#   Brasil  brbr
[[sedes]]
name = "Brasil"
contest = "Brasil"
premiacao = false
codes = ["teambr"]
ouro = 3
prata = 6
bronze = 10

# MEXICO
#   Mexico  mxmx
[[sedes]]
name = "Mexico"
contest = "Mexico"
premiacao = false
codes = ["teammx"]

# Central America
#   Costa Rica  cacr
#   El Salvador  cael
#   Guatemala  cagt
[[sedes]]
name = "Central America"
contest = "Central America"
premiacao = false
codes = ["teamca"]

[[sedes]]
name = "Costa Rica"
contest = "Central America"
premiacao = false
codes = ["teamcacr"]

[[sedes]]
name = "El Salvador"
contest = "Central America"
premiacao = false
codes = ["teamcael"]

[[sedes]]
name = "Guatemala"
contest = "Central America"
premiacao = false
codes = ["teamcagt"]


# Caribbean
#   Cuba  cbcu
#   Dominican Republic  cbdr
#   Puerto Rico  cbpr
#   Trinidad and Tobago  cbtt
#   Antigua and Barbuda  cbab
[[sedes]]
name = "Caribbean"
contest = "Caribbean"
premiacao = false
codes = ["teamcb"]

[[sedes]]
name = "Cuba"
contest = "Caribbean"
premiacao = false
codes = ["teamcbcu"]

[[sedes]]
name = "Dominican Republic"
contest = "Caribbean"
premiacao = false
codes = ["teamcbdr"]

[[sedes]]
name = "Puerto Rico"
contest = "Caribbean"
premiacao = false
codes = ["teamcbpr"]

[[sedes]]
name = "Trinidad and Tobago"
contest = "Caribbean"
premiacao = false
codes = ["teamcbtt"]

[[sedes]]
name = "Antigua and Barbuda"
contest = "Caribbean"
premiacao = false
codes = ["teamcbab"]
