salt = "salt"

[[secrets]]
name = "Latin America"
secret = "Latin America"

[[secrets]]
name = "North"
secret = "North"

[[secrets]]
name = "Colombia"
secret = "Colombia"

[[secrets]]
name = "Venezuela"
secret = "Venezuela"

[[secrets]]
name = "South"
secret = "South"

[[secrets]]
name = "Argentina"
secret = "Argentina"

[[secrets]]
name = "Bolivia"
secret = "Bolivia"

[[secrets]]
name = "Chile"
secret = "Chile"

[[secrets]]
name = "Peru"
secret = "Peru"

[[secrets]]
name = "Brasil"
secret = "Brasil"

[[secrets]]
name = "Mexico"
secret = "Mexico"

[[secrets]]
name = "Central America"
secret = "Central America"

[[secrets]]
name = "Costa Rica"
secret = "Costa Rica"

[[secrets]]
name = "El Salvador"
secret = "El Salvador"

[[secrets]]
name = "Guatemala"
secret = "Guatemala"

[[secrets]]
name = "Caribbean"
secret = "Caribbean"

[[secrets]]
name = "Cuba"
secret = "Cuba"

[[secrets]]
name = "Dominican Republic"
secret = "Dominican Republic"

[[secrets]]
name = "Puerto Rico"
secret = "Puerto Rico"

[[secrets]]
name = "Trinidad and Tobago"
secret = "Trinidad and Tobago"

[[secrets]]
name = "Antigua and Barbuda"
secret = "Antigua and Barbuda"
