titulo = "ICPC Latin America Regional CCL Contest"

[[sedes]]
name = "Latin America CCL"
contest = "Latin America CCL"
premiacao = false
codes = ["ccl"]
ouro = 3
prata = 6
bronze = 10

# NORTH
#   Colombia  noco
#   Venezuela  novz
[[sedes]]
name = "North CCL"
contest = "North CCL"
premiacao = false
codes = ["cclno"]

[[sedes]]
name = "Colombia CCL"
contest = "North CCL"
premiacao = false
codes = ["cclnoco"]

[[sedes]]
name = "Venezuela CCL"
contest = "North CCL"
premiacao = false
codes = ["cclnovz"]

# SOUTH
#   Argentina  soar
#   Bolivia  sobo
#   Chile  soch
#   Peru  sope
[[sedes]]
name = "South CCL"
contest = "South CCL"
premiacao = false
codes = ["cclso"]

[[sedes]]
name = "Argentina CCL"
contest = "South CCL"
premiacao = false
codes = ["cclsoar"]

[[sedes]]
name = "Bolivia CCL"
contest = "South CCL"
premiacao = false
codes = ["cclsobo"]

[[sedes]]
name = "Chile CCL"
contest = "South CCL"
premiacao = false
codes = ["cclsoch"]

[[sedes]]
name = "Peru CCL"
contest = "South CCL"
premiacao = false
codes = ["cclsope"]


# BRASIL
#   Brasil  brbr
[[sedes]]
name = "Brasil CCL"
contest = "Brasil CCL"
premiacao = false
codes = ["cclbr"]
ouro = 3
prata = 6
bronze = 10

# MEXICO
#   Mexico  mxmx
[[sedes]]
name = "Mexico CCL"
contest = "Mexico CCL"
premiacao = false
codes = ["cclmx"]

# Central America
#   Costa Rica  cacr
#   El Salvador  cael
#   Guatemala  cagt
[[sedes]]
name = "Central America CCL"
contest = "Central America CCL"
premiacao = false
codes = ["cclca"]

[[sedes]]
name = "Costa Rica CCL"
contest = "Central America CCL"
premiacao = false
codes = ["cclcacr"]

[[sedes]]
name = "El Salvador CCL"
contest = "Central America CCL"
premiacao = false
codes = ["cclcael"]

[[sedes]]
name = "Guatemala CCL"
contest = "Central America CCL"
premiacao = false
codes = ["cclcagt"]


# Caribbean
#   Cuba  cbcu
#   Dominican Republic  cbdr
#   Puerto Rico  cbpr
#   Trinidad and Tobago  cbtt
#   Antigua and Barbuda  cbab
[[sedes]]
name = "Caribbean CCL"
contest = "Caribbean CCL"
premiacao = false
codes = ["cclcb"]

[[sedes]]
name = "Cuba CCL"
contest = "Caribbean CCL"
premiacao = false
codes = ["cclcbcu"]

[[sedes]]
name = "Dominican Republic CCL"
contest = "Caribbean CCL"
premiacao = false
codes = ["cclcbdr"]

[[sedes]]
name = "Puerto Rico CCL"
contest = "Caribbean CCL"
premiacao = false
codes = ["cclcbpr"]

[[sedes]]
name = "Trinidad and Tobago CCL"
contest = "Caribbean CCL"
premiacao = false
codes = ["cclcbtt"]

[[sedes]]
name = "Antigua and Barbuda CCL"
contest = "Caribbean CCL"
premiacao = false
codes = ["cclcbab"]
