salt = "salt"

[[secrets]]
name = "North CCL"
secret = "North CCL"

[[secrets]]
name = "South CCL"
secret = "South CCL"

[[secrets]]
name = "Brasil CCL"
secret = "Brasil CCL"

[[secrets]]
name = "Mexico CCL"
secret = "Mexico CCL"

[[secrets]]
name = "Central America CCL"
secret = "Central America CCL"

[[secrets]]
name = "Caribbean CCL"
secret = "Caribbean CCL"
