salt = "salt"

[[secrets]]
name = "North"
secret = "North"

[[secrets]]
name = "South"
secret = "South"

[[secrets]]
name = "Brasil"
secret = "Brasil"

[[secrets]]
name = "Mexico"
secret = "Mexico"

[[secrets]]
name = "Central America"
secret = "Central America"

[[secrets]]
name = "Caribbean"
secret = "Caribbean"
