titulo = "ICPC Latin America Regional Contest"

[[sedes]]
name = "Latin America"
contest = "Latin America"
premiacao = false
codes = ["team"]
ouro = 3
prata = 6
bronze = 10
# NORTH
#   Colombia  noco
#   Venezuela  novz
[[sedes]]
name = "North"
contest = "North"
premiacao = false
codes = ["teamno"]

# SOUTH
#   Argentina  soar
#   Bolivia  sobo
#   Chile  soch
#   Peru  sope
[[sedes]]
name = "South"
contest = "South"
premiacao = false
codes = ["teamso"]

# BRASIL
#   Brasil  brbr
[[sedes]]
name = "Brasil"
contest = "Brasil"
premiacao = false
codes = ["teambr"]
ouro = 3
prata = 6
bronze = 10

# MEXICO
#   Mexico  mxmx
[[sedes]]
name = "Mexico"
contest = "Mexico"
premiacao = false
codes = ["teammx"]

# Central America
#   Costa Rica  cacr
#   El Salvador  cael
#   Guatemala  cagt
[[sedes]]
name = "Central America"
contest = "Central America"
premiacao = false
codes = ["teamca"]

# Caribbean
#   Cuba  cbcu
#   Dominican Republic  cbdr
#   Puerto Rico  cbpr
#   Trinidad and Tobago  cbtt
#   Antigua and Barbuda  cbab
[[sedes]]
name = "Caribbean"
contest = "Caribbean"
premiacao = false
codes = ["teamcb"]
