salt = "salt"

[[secrets]]
name = "Latin America CCL"
secret = "Latin America CCL"

[[secrets]]
name = "North CCL"
secret = "North CCL"

[[secrets]]
name = "Colombia CCL"
secret = "Colombia CCL"

[[secrets]]
name = "Venezuela CCL"
secret = "Venezuela CCL"

[[secrets]]
name = "South CCL"
secret = "South CCL"

[[secrets]]
name = "Argentina CCL"
secret = "Argentina CCL"

[[secrets]]
name = "Bolivia CCL"
secret = "Bolivia CCL"

[[secrets]]
name = "Chile CCL"
secret = "Chile CCL"

[[secrets]]
name = "Peru CCL"
secret = "Peru CCL"

[[secrets]]
name = "Brasil CCL"
secret = "Brasil CCL"

[[secrets]]
name = "Mexico CCL"
secret = "Mexico CCL"

[[secrets]]
name = "Central America CCL"
secret = "Central America CCL"

[[secrets]]
name = "Costa Rica CCL"
secret = "Costa Rica CCL"

[[secrets]]
name = "El Salvador CCL"
secret = "El Salvador CCL"

[[secrets]]
name = "Guatemala CCL"
secret = "Guatemala CCL"

[[secrets]]
name = "Caribbean CCL"
secret = "Caribbean CCL"

[[secrets]]
name = "Cuba CCL"
secret = "Cuba CCL"

[[secrets]]
name = "Dominican Republic CCL"
secret = "Dominican Republic CCL"

[[secrets]]
name = "Puerto Rico CCL"
secret = "Puerto Rico CCL"

[[secrets]]
name = "Trinidad and Tobago CCL"
secret = "Trinidad and Tobago CCL"

[[secrets]]
name = "Antigua and Barbuda CCL"
secret = "Antigua and Barbuda CCL"
