
salt = "salt"

[[secrets]]
name = "Brasil"
secret = "Brasil"

[[secrets]]
name = "Chile"
secret = "Chile"

[[secrets]]
name = "Mexico"
secret = "Mexico"

[[secrets]]
name = "Bolivia"
secret = "Bolivia"

[[secrets]]
name = "Centro America"
secret = "Centro"

