titulo = "ICPC Regionals CCL Brasil"

[[sedes]]
codes = [
  "brdfdf23ccl",
  "brpeol23ccl",
  "brsesc23ccl",
  "brceqx23ccl",
  "bracrb23ccl",
  "brmgud23ccl",
  "brmgsr23ccl",
]
name = "CCLBrasil"
premiacao = false
contest = "CCLBrasil"

[[sedes]]
codes = ["brdfdf23ccl"]
name = "CCL Brasil 1"
premiacao = false
contest = "CCLBrasil"
[[sedes]]
codes = ["brpeol23ccl"]
name = "CCL Brasil 2"
premiacao = false
contest = "CCLBrasil"
[[sedes]]
codes = ["brsesc23ccl"]
name = "CCL Brasil 3"
premiacao = false
contest = "CCLBrasil"
[[sedes]]
codes = ["brceqx23ccl"]
name = "CCL Brasil 4"
premiacao = false
contest = "CCLBrasil"
[[sedes]]
codes = ["bracrb23ccl"]
name = "CCL Brasil 5"
premiacao = false
contest = "CCLBrasil"
[[sedes]]
codes = ["brmgud23ccl"]
name = "CCL Brasil 6"
premiacao = false
contest = "CCLBrasil"
[[sedes]]
codes = ["brmgsr23ccl"]
name = "CCL Brasil 7"
premiacao = false
contest = "CCLBrasil"
