[titulo]
name = "Maratona de Programação da SBC - 1ª fase"
codes = [""]
ouro = 1
prata = 2
bronze = 3

[[sedes]]
name = "Brasil"
codes = [
  "pait23",
  "mtcu23",
  "acrb23",
  "papa23",
  "ropv23",
  "amma23",
  "peol23",
  "sesc23",
  "masl23",
  "pite23",
  "ceju23",
  "pbcg23",
  "rnna23",
  "maba23",
  "baju23",
  "cefo23",
  "basa23",
  "rnpf23",
  "alma23",
  "ceqx23",
  "mscg23",
  "gogo23",
  "dfdf23",
  "mgmc23",
  "mgti23",
  "spba23",
  "spta23",
  "mgsj23",
  "mgbh23",
  "spso23",
  "mgud23",
  "spbs23",
  "rjrj23",
  "spsp23",
  "mgub23",
  "mgsr23",
  "mgvi23",
  "mgvi23",
  "scfl23",
  "prcm23",
  "prcu23",
  "scch23",
  "rsij23",
  "prto23",
  "rspa23",
]
premiacao = false
vagas = 0
contest = "Brasil"

[[sedes]]
name = "Região Norte"
codes = ["pait23", "acrb23", "papa23", "ropv23", "amma23"]
premiacao = false
vagas = 0
contest = "Brasil"

[[sedes]]
name = "Região Nordeste"
codes = [
  "peol23",
  "sesc23",
  "masl23",
  "pite23",
  "ceju23",
  "pbcg23",
  "rnna23",
  "maba23",
  "baju23",
  "cefo23",
  "basa23",
  "rnpf23",
  "alma23",
  "ceqx23",
]
premiacao = false
vagas = 0
contest = "Brasil"

[[sedes]]
name = "Região Centro-Oeste"
codes = ["mtcu23", "mscg23", "gogo23", "dfdf23"]
premiacao = false
vagas = 0
contest = "Brasil"

[[sedes]]
name = "Região Sudeste"
codes = [
  "mgmc23",
  "mgti23",
  "spba23",
  "spta23",
  "mgsj23",
  "mgbh23",
  "spso23",
  "mgud23",
  "spbs23",
  "rjrj23",
  "spsp23",
  "mgub23",
  "mgsr23",
  "mgvi23",
  "mgvi23",
]
premiacao = false
vagas = 0
contest = "Brasil"

[[sedes]]
name = "Região Sul"
codes = ["scfl23", "prcm23", "prcu23", "scch23", "rsij23", "prto23", "rspa23"]
premiacao = false
vagas = 0
contest = "Brasil"

# :MS:Campo Grande
[[sedes]]
name = "Campo Grande"
codes = ["mscg23"]
contest = "Brasil"
premiacao = false


# :PA:Itaituba
[[sedes]]
name = "Itaituba"
codes = ["pait23"]
contest = "Brasil"
premiacao = false


# :MT:Cuiabá
[[sedes]]
name = "Cuiabá"
codes = ["mtcu23"]
contest = "Brasil"
premiacao = false


# :GO:Goiânia
[[sedes]]
name = "Goiânia"
codes = ["gogo23"]
contest = "Brasil"
premiacao = false


# :DF:Brasília
[[sedes]]
name = "Brasília"
codes = ["dfdf23"]
contest = "Brasil"
premiacao = false


# :PE:Olinda
[[sedes]]
name = "Olinda"
codes = ["peol23"]
contest = "Brasil"
premiacao = false


# :SE:São Cristóvão
[[sedes]]
name = "São Cristóvão"
codes = ["sesc23"]
contest = "Brasil"
premiacao = false


# :MA:São Luís
[[sedes]]
name = "São Luís"
codes = ["masl23"]
contest = "Brasil"
premiacao = false


# :PI:Teresina
[[sedes]]
name = "Teresina"
codes = ["pite23"]
contest = "Brasil"
premiacao = false


# :CE:Juazeiro do Norte
[[sedes]]
name = "Juazeiro do Norte"
codes = ["ceju23"]
contest = "Brasil"
premiacao = false


# :PB:Campina Grande
[[sedes]]
name = "Campina Grande"
codes = ["pbcg23"]
contest = "Brasil"
premiacao = false


# :RN:Natal
[[sedes]]
name = "Natal"
codes = ["rnna23"]
contest = "Brasil"
premiacao = false


# :MA:Balsas
[[sedes]]
name = "Balsas"
codes = ["maba23"]
contest = "Brasil"
premiacao = false


# :BA:Juazeiro
[[sedes]]
name = "Juazeiro"
codes = ["baju23"]
contest = "Brasil"
premiacao = false


# :CE:Fortaleza
[[sedes]]
name = "Fortaleza"
codes = ["cefo23"]
contest = "Brasil"
premiacao = false


# :BA:Salvador
[[sedes]]
name = "Salvador"
codes = ["basa23"]
contest = "Brasil"
premiacao = false


# :RN:Pau dos Ferros
[[sedes]]
name = "Pau dos Ferros"
codes = ["rnpf23"]
contest = "Brasil"
premiacao = false


# :AL:Maceió
[[sedes]]
name = "Maceió"
codes = ["alma23"]
contest = "Brasil"
premiacao = false


# :CE:Quixadá
[[sedes]]
name = "Quixadá"
codes = ["ceqx23"]
contest = "Brasil"
premiacao = false


# :AC:Rio Branco
[[sedes]]
name = "Rio Branco"
codes = ["acrb23"]
contest = "Brasil"
premiacao = false


# :PA:Paragominas
[[sedes]]
name = "Paragominas"
codes = ["papa23"]
contest = "Brasil"
premiacao = false


# :RO:Porto Velho
[[sedes]]
name = "Porto Velho"
codes = ["ropv23"]
contest = "Brasil"
premiacao = false


# :AM:Manaus
[[sedes]]
name = "Manaus"
codes = ["amma23"]
contest = "Brasil"
premiacao = false


# :MG:Montes Claros
[[sedes]]
name = "Montes Claros"
codes = ["mgmc23"]
contest = "Brasil"
premiacao = false


# :MG:Timóteo
[[sedes]]
name = "Timóteo"
codes = ["mgti23"]
contest = "Brasil"
premiacao = false


# :SP:Bauru
[[sedes]]
name = "Bauru"
codes = ["spba23"]
contest = "Brasil"
premiacao = false


# :SP:Taubaté
[[sedes]]
name = "Taubaté"
codes = ["spta23"]
contest = "Brasil"
premiacao = false


# :MG:São João del-Rei
[[sedes]]
name = "São João del-Rei"
codes = ["mgsj23"]
contest = "Brasil"
premiacao = false


# :MG:Belo Horizonte
[[sedes]]
name = "Belo Horizonte"
codes = ["mgbh23"]
contest = "Brasil"
premiacao = false


# :SP:Sorocaba
[[sedes]]
name = "Sorocaba"
codes = ["spso23"]
contest = "Brasil"
premiacao = false


# :MG:Uberlândia
[[sedes]]
name = "Uberlândia"
codes = ["mgud23"]
contest = "Brasil"
premiacao = false


# :SP:Barretos
[[sedes]]
name = "Barretos"
codes = ["spbs23"]
contest = "Brasil"
premiacao = false


# :RJ:Rio de Janeiro
[[sedes]]
name = "Rio de Janeiro"
codes = ["rjrj23"]
contest = "Brasil"
premiacao = false


# :SP:São Paulo
[[sedes]]
name = "São Paulo"
codes = ["spsp23"]
contest = "Brasil"
premiacao = false


# :MG:Uberaba
[[sedes]]
name = "Uberaba"
codes = ["mgub23"]
contest = "Brasil"
premiacao = false


# :MG:Santa Rita do Sapucaí
[[sedes]]
name = "Santa Rita do Sapucaí"
codes = ["mgsr23"]
contest = "Brasil"
premiacao = false


# :MG:Viçosa
[[sedes]]
name = "Viçosa"
codes = ["mgvi23"]
contest = "Brasil"
premiacao = false


# :SC:Florianópolis
[[sedes]]
name = "Florianópolis"
codes = ["scfl23"]
contest = "Brasil"
premiacao = false


# :PR:Campo Mourão
[[sedes]]
name = "Campo Mourão"
codes = ["prcm23"]
contest = "Brasil"
premiacao = false


# :PR:Curitiba
[[sedes]]
name = "Curitiba"
codes = ["prcu23"]
contest = "Brasil"
premiacao = false


# :SC:Chapecó
[[sedes]]
name = "Chapecó"
codes = ["scch23"]
contest = "Brasil"
premiacao = false


# :RS:Ijuí
[[sedes]]
name = "Ijuí"
codes = ["rsij23"]
contest = "Brasil"
premiacao = false


# :PR:Toledo
[[sedes]]
name = "Toledo"
codes = ["prto23"]
contest = "Brasil"
premiacao = false


# :RS:Porto Alegre
[[sedes]]
name = "Porto Alegre"
codes = ["rspa23"]
contest = "Brasil"
premiacao = false


[[sedes]]
name = "Bolivia"
contest = "Bolivia"
premiacao = false
codes = [
  "sobolp23",
  "soboco23",
  "sobota23",
  "sobotr23",
  "sobosc23",
  "sobocb23",
  "sobobe23",
  "soboor23",
  "soboya23",
  "sobotu23",
  "soboea23",
  "soboll23",
  "sobopo23",
  "sobosu23",
]

[[sedes]]
name = "La Paz"
codes = ["sobolp23"]
premiacao = false
contest = "Bolivia"

[[sedes]]
name = "Cochabamba"
codes = ["soboco23"]
premiacao = false
contest = "Bolivia"

[[sedes]]
name = "Tarija"
codes = ["sobota23"]
premiacao = false
contest = "Bolivia"

[[sedes]]
name = "Trinidad"
codes = ["sobotr23"]
premiacao = false
contest = "Bolivia"

[[sedes]]
name = "Santa Cruz"
codes = ["sobosc23"]
premiacao = false
contest = "Bolivia"

[[sedes]]
name = "Cobija"
codes = ["sobocb23"]
premiacao = false
contest = "Bolivia"

[[sedes]]
name = "Bermejo"
codes = ["sobobe23"]
premiacao = false
contest = "Bolivia"

[[sedes]]
name = "Oruro"
codes = ["soboor23"]
premiacao = false
contest = "Bolivia"

[[sedes]]
name = "Yacuiba"
codes = ["soboya23"]
premiacao = false
contest = "Bolivia"

[[sedes]]
name = "Tupiza"
codes = ["sobotu23"]
premiacao = false
contest = "Bolivia"

[[sedes]]
name = "El Alto"
codes = ["soboea23"]
premiacao = false
contest = "Bolivia"

[[sedes]]
name = "Llallagua"
codes = ["soboll23"]
premiacao = false
contest = "Bolivia"

[[sedes]]
name = "Potosí"
codes = ["sobopo23"]
premiacao = false
contest = "Bolivia"

[[sedes]]
name = "Sucre"
codes = ["sobosu23"]
premiacao = false
contest = "Bolivia"


# CHILE
[[sedes]]
name = "Chile"
codes = ["chsaud23", "chrauo23", "chcouc23", "chsaut23", "chcoud23", "chtauc23"]
premiacao = false
contest = "Chile"

[[sedes]]
codes = ["chsaud23"]
name = "Santiago (UDP)"
premiacao = false
contest = "Chile"

[[sedes]]
codes = ["chrauo23"]
name = "Rancagua (UOH)"
premiacao = false
contest = "Chile"

[[sedes]]
codes = ["chcouc23"]
name = "Coquimbo / La Serena (UCN)"
premiacao = false
contest = "Chile"

[[sedes]]
codes = ["chsaut23"]
name = "Santiago (UTFSM)"
premiacao = false
contest = "Chile"

[[sedes]]
codes = ["chcoud23"]
name = "Concepción (UdeC)"
premiacao = false
contest = "Chile"

[[sedes]]
codes = ["chtauc23"]
name = "Talca (UCM)"
premiacao = false
contest = "Chile"


# MEXICO
[[sedes]]
codes = [
  "mxitrr",
  "mxitcx",
  "mxitza",
  "mxitzo",
  "mxitpu",
  "mxtnml",
  "mxicul",
  "mxitrv",
  "mxitsz",
  "mxitsv",
  "mxitoh",
  "mxitoc",
  "mxitph",
  "mxitck",
  "mxitcm",
  "mxitpz",
  "mxitch",
  "mxitox",
  "mxitco",
  "mxuayc",
  "mxitpn",
  "mxitnl",
  "mxitcl",
  "mxitap",
  "mxitcn",
  "mxitmo",
  "mxitcz",
  "mxithe",
  "mxitur",
  "mxitcj",
  "mxitsg",
  "mxuasi",
  "mxiver",
  "mximan",
  "mxitlr",
  "mxlzcr",
  "mxisur",
  "mxitlg",
  "mxuacj",
  "mxuton",
  "mxucos",
  "mxnmig",
  "mxnmci",
  "mxcipn",
  "mxuoax",
  "mxupab",
  "mxupag",
  "mxumor",
  "mxtmcv",
  "mxcnnu",
  "mxcuat",
  "mxuval",
  "mxupub",
  "mxucei",
  "mxcuaz",
  "mxslpt",
  "mxuanl",
  "mxttol",
  "mxtmcp",
  "mxmont",
  "mxtmem",
  "mxuaeh",
  "mxugnj",
  "mxomif",
  "mxuach",
  "mxsujs",
  "mxuaag",
  "mxmari",
  "mxtmmx",
  "mxumsn",
  "mxuayt",
  "mxumon",
  "mxfims",
  "mxquer",
]
name = "Mexico"
premiacao = false
contest = "Mexico"


[[sedes]]
codes = ["mxitrr"]
name = "Instituto Tecnológico de Parral"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitcx"]
name = "Instituto Tecnológico Superior de Comalcaco"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitza"]
name = "Instituto Tecnológico de Zacatepec"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitzo"]
name = "Instituto Tecnológico Superior de Zongolica"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitpu"]
name = "Instituto Tecnológico Superior de Purísima del Rincón"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxtnml"]
name = "Instituto Tecnológico de León"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxicul"]
name = "Instituto Tecnológico de Culiacán"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitrv"]
name = "Instituto Tecnológico Superior de Rioverde"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitsz"]
name = "Instituto Tecnológico y de Estudios Superiores de Zamora"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitsv"]
name = "Instituto Tecnológico Superior de Salvatierra"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitoh"]
name = "Instituto Tecnológico Superior del Oriente del Estado de Hidalgo"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitoc"]
name = "Instituto Tecnologico Superior del Occidente del Estado de Hidalgo"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitph"]
name = "Instituto Tecnológico de Pachuca"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitck"]
name = "Instituto Tecnológico Superior de Calkiní"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitcm"]
name = "Instituto Tecnológico de Ciudad Madero"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitpz"]
name = "Instituto Tecnológico Superior de Pátzcuaro"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitch"]
name = "Instituto Tecnológico Superior de Ciudad Hidalgo"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitox"]
name = "Instituto Tecnológico de Oaxaca"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitco"]
name = "Instituto Tecnológico de Comitán"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxuayc"]
name = "Universidad Autónoma de Yucatán"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitpn"]
name = "Instituto Tecnológico de Piedras Negras"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitnl"]
name = "Instituto Tecnológico de Nuevo León"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitcl"]
name = "Instituto Tecnológico de Celaya"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitap"]
name = "Instituto Tecnológico Superior de Apatzingán"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitcn"]
name = "Instituto Tecnológico de Cancún"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitmo"]
name = "Instituto Tecnológico de Morelia"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitcz"]
name = "Instituto Tecnológico Superior de Coatzacoalcos"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxithe"]
name = "Instituto Tecnológico Superior de Huetamo"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitur"]
name = "Instituto Tecnológico Superior de Uruapan"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitcj"]
name = "Instituto Tecnológico de Ciudad Juárez"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitsg"]
name = "ACM Campus ITESG"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxuasi"]
name = "Coding CUP Sinaloa"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxiver"]
name = "Comunidad Estudiantil de Programación Competitiva de Instituto Tecnológico de Veracruz"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mximan"]
name = "Sistemas Computacionales ITS Mante"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitlr"]
name = "ACM ICPC Algorithmia ITSLerdo"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxlzcr"]
name = "Programación Lázaro Cárdenas"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxisur"]
name = "Coding CUP ITSUR"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxitlg"]
name = "Club de Programación Competitiva ITLag"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxuacj"]
name = "UACJ Algorithmic Club"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxuton"]
name = "Universidad de Guadalajara CUTonalá"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxucos"]
name = "Universidad de Guadalajara CUCOSTA"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxnmig"]
name = "UNAM Facultad de Ingeniería - Club de Programación Competitiva"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxnmci"]
name = "UNAM Facultad de Ciencias - Club de Programación Competitiva"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxcipn"]
name = "Red Académica de Programación Competitiva del Instituto Politécnico Nacional / UNAM FES Acatlán / UAM / ITAM"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxuoax"]
name = "Universidad Anahuac Oaxaca"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxupab"]
name = "Universidad Panamericana Campus Bonaterra"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxupag"]
name = "Universidad Panamericana Campus Guadalajara"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxumor"]
name = "Escuela Nacional de Estudios Superiores UNAM Campus Morelia"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxtmcv"]
name = "Tecnologico de Monterrey Cuernavaca"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxcnnu"]
name = "Centro de Nanociencias y Nanotecnologia UNAM"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxcuat"]
name = "Capitulo Estudiantil UAT ACM"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxuval"]
name = "Club de Algoritmia CUValles"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxupub"]
name = "CPU - Programación Competitiva Universidad Popular Autónoma del Estado de Puebla"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxucei"]
name = "CAC - Club de Algoritmia CUCEI"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxcuaz"]
name = "Club de Programación Competitiva UAZ"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxslpt"]
name = "ICPC San Luis Potosi"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxuanl"]
name = "ACM Universidad Autonoma de Nuevo Leon"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxttol"]
name = "Programación Competitiva Tec Toluca"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxtmcp"]
name = "Programación Competitiva Tec de Monterrey Puebla"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxmont"]
name = "ACM Monterrey"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxtmem"]
name = "Programación Competitiva Tec de Monterrey Campus Estado de México"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxuaeh"]
name = "Universidad Autónoma del Estado de Hidalgo"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxugnj"]
name = "Universidad de Guanajuato"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxomif"]
name = "Olimpiada Mexicana de Informatica"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxuach"]
name = "Universidad Autonoma de Chihuahua"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxsujs"]
name = "Sistema Universitario Jesuita"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxuaag"]
name = "Universidad Autonoma de Aguascalientes"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxmari"]
name = "Universidad Marista de Guadalajara"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxtmmx"]
name = "Tecnológico de Monterrey Campus Ciudad de México"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxumsn"]
name = "Universidad Michoacana de San Nicolás de Hidalgo"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxuayt"]
name = "Universidad Autónoma de Yucatan Unidad Multidisciplinaria Tizimín"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxumon"]
name = "Universidad de Monterrey"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxfims"]
name = "Facultad de Informática Mazatlán Universidad Autónoma de Sinaloa"
premiacao = false
contest = "Mexico"

[[sedes]]
codes = ["mxquer"]
name = "ACM Querétaro"
premiacao = false
contest = "Mexico"

#Centro America

[[sedes]]
codes = [
  "caurlq23",
  "caufla23",
  "cacrsp23",
  "caujsc23",
  "cananm23",
  "catcrs23",
  "caucrp23",
  "cauncn23",
  "caunco23",
  "catcrl23",
  "caumgg23",
  "catcra23",
]
name = "Centro America"
premiacao = false
contest = "Centro America"


[[sedes]]
codes = ["caurlq23"]
name = "Universidad Rafael Landívar sede Quetzaltenango"
premiacao = false
contest = "Centro America"

[[sedes]]
codes = ["caufla23"]
name = "Universidad Rafael Landívar"
premiacao = false
contest = "Centro America"

[[sedes]]
codes = ["cacrsp23"]
name = "Universidad de Costa Rica sede San Pedro"
premiacao = false
contest = "Centro America"

[[sedes]]
codes = ["caujsc23"]
name = "Universidad Centroamericana José Simeón Cañas"
premiacao = false
contest = "Centro America"

[[sedes]]
codes = ["cananm23"]
name = "Universidad Nacional Autónoma de Nicaragua sede Managua"
premiacao = false
contest = "Centro America"

[[sedes]]
codes = ["catcrs23"]
name = "Tecnológico de Costa Rica Sede Cartago"
premiacao = false
contest = "Centro America"

[[sedes]]
codes = ["caucrp23"]
name = "Universidad de Costa Rica Pacífico"
premiacao = false
contest = "Centro America"

[[sedes]]
codes = ["cauncn23"]
name = "Universidad Nacional Chorotega - Nicoya"
premiacao = false
contest = "Centro America"

[[sedes]]
codes = ["caunco23"]
name = "Universidad Nacional sede Coto"
premiacao = false
contest = "Centro America"

[[sedes]]
codes = ["catcrl23"]
name = "Tecnológico de Costa Rica sede Limón"
premiacao = false
contest = "Centro America"

[[sedes]]
codes = ["caumgg23"]
name = "Universidad Mariano Galvez de Guatemala Campus Chiquimulilla"
premiacao = false
contest = "Centro America"

[[sedes]]
codes = ["catcra23"]
name = "Tecnológico de Costa Rica Sede Alajuela"
premiacao = false
contest = "Centro America"
