[titulo]
name = "Bolivia"
codes = ["teamsobo"]


[[sedes]]
name = "Bolivia"
codes = [
  "sobolp23",
  "soboco23",
  "sobota23",
  "sobotr23",
  "sobosc23",
  "sobocb23",
  "sobobe23",
  "soboor23",
  "soboya23",
  "sobotu23",
  "soboea23",
  "soboll23",
  "sobopo23",
  "sobosu23",
]

[[sedes]]
name = "La Paz"
codes = ["sobolp23"]

[[sedes]]
name = "Cochabamba"
codes = ["soboco23"]

[[sedes]]
name = "Tarija"
codes = ["sobota23"]

[[sedes]]
name = "Trinidad"
codes = ["sobotr23"]

[[sedes]]
name = "Santa Cruz"
codes = ["sobosc23"]

[[sedes]]
name = "Cobija"
codes = ["sobocb23"]

[[sedes]]
name = "Bermejo"
codes = ["sobobe23"]

[[sedes]]
name = "Oruro"
codes = ["soboor23"]

[[sedes]]
name = "Yacuiba"
codes = ["soboya23"]

[[sedes]]
name = "Tupiza"
codes = ["sobotu23"]

[[sedes]]
name = "El Alto"
codes = ["soboea23"]

[[sedes]]
name = "Llallagua"
codes = ["soboll23"]

[[sedes]]
name = "Potosí"
codes = ["sobopo23"]

[[sedes]]
name = "Sucre"
codes = ["sobosu23"]
