[titulo]
name = "Maratona de Programação da SBC"
codes = ["teambr"]
ouro = 4
prata = 8
bronze = 12

[[sedes]]
name = "Brasil"
codes = [
  "pait23",
  "mtcu23",
  "acrb23",
  "papa23",
  "ropv23",
  "amma23",
  "peol23",
  "sesc23",
  "masl23",
  "pite23",
  "ceju23",
  "pbcg23",
  "rnna23",
  "maba23",
  "baju23",
  "cefo23",
  "basa23",
  "rnpf23",
  "alma23",
  "ceqx23",
  "mscg23",
  "gogo23",
  "dfdf23",
  "mgmc23",
  "mgti23",
  "spba23",
  "spta23",
  "mgsj23",
  "mgbh23",
  "spso23",
  "mgud23",
  "spbs23",
  "rjrj23",
  "spsp23",
  "mgub23",
  "mgsr23",
  "mgvi23",
  "mgvi23",
  "scfl23",
  "prcm23",
  "prcu23",
  "scch23",
  "rsij23",
  "prto23",
  "rspa23",
]
ouro = 4
prata = 8
bronze = 12

[[sedes]]
name = "Região Norte"
codes = ["pait23", "acrb23", "papa23", "ropv23", "amma23"]

[[sedes]]
name = "Região Nordeste"
codes = [
  "peol23",
  "sesc23",
  "masl23",
  "pite23",
  "ceju23",
  "pbcg23",
  "rnna23",
  "maba23",
  "baju23",
  "cefo23",
  "basa23",
  "rnpf23",
  "alma23",
  "ceqx23",
]

[[sedes]]
name = "Região Centro-Oeste"
codes = ["mtcu23", "mscg23", "gogo23", "dfdf23"]

[[sedes]]
name = "Região Sudeste"
codes = [
  "mgmc23",
  "mgti23",
  "spba23",
  "spta23",
  "mgsj23",
  "mgbh23",
  "spso23",
  "mgud23",
  "spbs23",
  "rjrj23",
  "spsp23",
  "mgub23",
  "mgsr23",
  "mgvi23",
  "mgvi23",
]

[[sedes]]
name = "Região Sul"
codes = ["scfl23", "prcm23", "prcu23", "scch23", "rsij23", "prto23", "rspa23"]

[[sedes]]
name = "Supersede Norte"
codes = ["pait23", "acrb23", "ropv23", "amma23"]

[[sedes]]
name = "Supersede Nordeste"
codes = ["sesc23", "masl23", "ceju23", "maba23", "baju23", "alma23", "ceqx23"]

[[sedes]]
name = "Supersede Centro Oeste"
codes = ["mtcu23", "mscg23", "gogo23", "dfdf23"]

[[sedes]]
name = "Supersede Sul"
codes = ["scfl23", "scch23", "rspa23"]

[[sedes]]
name = "Supersede Minas"
codes = ["mgmc23", "mgsj23", "mgud23", "mgvi23"]

[[sedes]]
name = "Supersede Parana"
codes = ["prcm23", "prcu23", "prto23"]

[[sedes]]
name = "Supersede RN"
codes = ["rnna23", "rnpf23"]

[[sedes]]
name = "Supersede Sao Paulo"
codes = ["spbs23", "spta23"]

# :MS:Campo Grande
[[sedes]]
name = "Campo Grande"
codes = ["mscg23"]

# :PA:Itaituba
[[sedes]]
name = "Itaituba"
codes = ["pait23"]

# :MT:Cuiabá
[[sedes]]
name = "Cuiabá"
codes = ["mtcu23"]

# :GO:Goiânia
[[sedes]]
name = "Goiânia"
codes = ["gogo23"]

# :DF:Brasília
[[sedes]]
name = "Brasília"
codes = ["dfdf23"]

# :PE:Olinda
[[sedes]]
name = "Olinda"
codes = ["peol23"]

# :SE:São Cristóvão
[[sedes]]
name = "São Cristóvão"
codes = ["sesc23"]

# :MA:São Luís
[[sedes]]
name = "São Luís"
codes = ["masl23"]

# :PI:Teresina
[[sedes]]
name = "Teresina"
codes = ["pite23"]

# :CE:Juazeiro do Norte
[[sedes]]
name = "Juazeiro do Norte"
codes = ["ceju23"]

# :PB:Campina Grande
[[sedes]]
name = "Campina Grande"
codes = ["pbcg23"]

# :RN:Natal
[[sedes]]
name = "Natal"
codes = ["rnna23"]

# :MA:Balsas
[[sedes]]
name = "Balsas"
codes = ["maba23"]

# :BA:Juazeiro
[[sedes]]
name = "Juazeiro"
codes = ["baju23"]

# :CE:Fortaleza
[[sedes]]
name = "Fortaleza"
codes = ["cefo23"]

# :BA:Salvador
[[sedes]]
name = "Salvador"
codes = ["basa23"]

# :RN:Pau dos Ferros
[[sedes]]
name = "Pau dos Ferros"
codes = ["rnpf23"]

# :AL:Maceió
[[sedes]]
name = "Maceió"
codes = ["alma23"]

# :CE:Quixadá
[[sedes]]
name = "Quixadá"
codes = ["ceqx23"]

# :AC:Rio Branco
[[sedes]]
name = "Rio Branco"
codes = ["acrb23"]

# :PA:Paragominas
[[sedes]]
name = "Paragominas"
codes = ["papa23"]

# :RO:Porto Velho
[[sedes]]
name = "Porto Velho"
codes = ["ropv23"]

# :AM:Manaus
[[sedes]]
name = "Manaus"
codes = ["amma23"]

# :MG:Montes Claros
[[sedes]]
name = "Montes Claros"
codes = ["mgmc23"]

# :MG:Timóteo
[[sedes]]
name = "Timóteo"
codes = ["mgti23"]

# :SP:Bauru
[[sedes]]
name = "Bauru"
codes = ["spba23"]

# :SP:Taubaté
[[sedes]]
name = "Taubaté"
codes = ["spta23"]

# :MG:São João del-Rei
[[sedes]]
name = "São João del-Rei"
codes = ["mgsj23"]

# :MG:Belo Horizonte
[[sedes]]
name = "Belo Horizonte"
codes = ["mgbh23"]

# :SP:Sorocaba
[[sedes]]
name = "Sorocaba"
codes = ["spso23"]

# :MG:Uberlândia
[[sedes]]
name = "Uberlândia"
codes = ["mgud23"]

# :SP:Barretos
[[sedes]]
name = "Barretos"
codes = ["spbs23"]

# :RJ:Rio de Janeiro
[[sedes]]
name = "Rio de Janeiro"
codes = ["rjrj23"]

# :SP:São Paulo
[[sedes]]
name = "São Paulo"
codes = ["spsp23"]

# :MG:Uberaba
[[sedes]]
name = "Uberaba"
codes = ["mgub23"]

# :MG:Santa Rita do Sapucaí
[[sedes]]
name = "Santa Rita do Sapucaí"
codes = ["mgsr23"]

# :MG:Viçosa
[[sedes]]
name = "Viçosa"
codes = ["mgvi23"]

# :SC:Florianópolis
[[sedes]]
name = "Florianópolis"
codes = ["scfl23"]

# :PR:Campo Mourão
[[sedes]]
name = "Campo Mourão"
codes = ["prcm23"]

# :PR:Curitiba
[[sedes]]
name = "Curitiba"
codes = ["prcu23"]

# :SC:Chapecó
[[sedes]]
name = "Chapecó"
codes = ["scch23"]

# :RS:Ijuí
[[sedes]]
name = "Ijuí"
codes = ["rsij23"]

# :PR:Toledo
[[sedes]]
name = "Toledo"
codes = ["prto23"]

# :RS:Porto Alegre
[[sedes]]
name = "Porto Alegre"
codes = ["rspa23"]
