[titulo]
name = "Brasil"
codes = ["teambr"]
ouro = 4
prata = 8
bronze = 12

[[sedes]]
name = "Brasil"
codes = ["teambr"]
ouro = 4
prata = 8
bronze = 12

[[sedes]]
name = "Região Norte"
codes = ["teambrac", "teambram", "teambrpa", "teambrro"]

[[sedes]]
name = "Região Nordeste"
codes = [
  "teambral",
  "teambrba",
  "teambrce",
  "teambrma",
  "teambrpb",
  "teambrpe",
  "teambrpi",
  "teambrrn",
  "teambrse",
]

[[sedes]]
name = "Região Centro-Oeste"
codes = ["teambrdf", "teambrgo", "teambrms", "teambrmt"]

[[sedes]]
name = "Região Sudeste"
codes = ["teambrmg", "teambrrj", "teambrsp"]

[[sedes]]
name = "Região Sul"
codes = ["teambrpr", "teambrrs", "teambrsc"]


[[sedes]]
codes = ["teambresvi"]
name = "ES, Vitoria"

[[sedes]]
codes = ["teambrpbcg"]
name = "PB, Campina Grande"

[[sedes]]
codes = ["teambrbaju"]
name = "BA, Juazeiro"

[[sedes]]
codes = ["teambrcefo"]
name = "CE, Fortaleza"

[[sedes]]
codes = ["teambrcejn"]
name = "CE, Juazeiro do Norte"

[[sedes]]
codes = ["teambrceqx"]
name = "CE, Quixada"

[[sedes]]
codes = ["teambrgogo"]
name = "GO, Goiania"

[[sedes]]
codes = ["teambrmaba"]
name = "MA, Balsas"

[[sedes]]
codes = ["teambrmgbh"]
name = "MG, Belo Horizonte"

[[sedes]]
codes = ["teambrmgmc"]
name = "MG, Montes Claros"

[[sedes]]
codes = ["teambrmscg"]
name = "MS, Campo Grande"

[[sedes]]
codes = ["teambrsptb"]
name = "SP, Taubate"

[[sedes]]
codes = ["teambrpite"]
name = "PI, Teresina"

[[sedes]]
codes = ["teambrrjrj"]
name = "RJ, Rio de Janeiro"

[[sedes]]
codes = ["teambrrnpf"]
name = "RN, Pau dos Ferros"

[[sedes]]
codes = ["teambrspsp"]
name = "SP, Sao Paulo"

[[sedes]]
codes = ["teambrropv"]
name = "RO, Porto Velho"

[[sedes]]
codes = ["teambrmgud"]
name = "MG, Uberlandia"

[[sedes]]
codes = ["teambrdfdf"]
name = "DF, Brasilia"

[[sedes]]
codes = ["teambrmgsr"]
name = "MG, Sao Joao de"

[[sedes]]
codes = ["teambrpeol"]
name = "PE, Olinda"

[[sedes]]
codes = ["teambrprcm"]
name = "PR, Campo Mourao"

[[sedes]]
codes = ["teambrrspa"]
name = "RS, Porto Alegre"

[[sedes]]
codes = ["teambrscfl"]
name = "SC, Florianopolis"

[[sedes]]
codes = ["teambrsesc"]
name = "SE, Sao Cristovao"

[[sedes]]
codes = ["teambrspso"]
name = "SP, Sorocaba"

[[sedes]]
codes = ["teambrmtcu"]
name = "MT, Cuiaba"

[[sedes]]
codes = ["teambrmgmu"]
name = "MG, Muzambinho"

[[sedes]]
codes = ["teambrmgpa"]
name = "MG, Patrocinio"

[[sedes]]
codes = ["teambrpabe"]
name = "PA, Belem"

[[sedes]]
codes = ["teambrpama"]
name = "PA, Maraba"

[[sedes]]
codes = ["teambrrspf"]
name = "RS, Passo Fundo"

[[sedes]]
codes = ["teambrspma"]
name = "SP, Marilia"

[[sedes]]
codes = ["teambrspsa"]
name = "SP, Santos"

[[sedes]]
codes = ["teambrpipa"]
name = "PI, Parnaiba"

[[sedes]]
codes = ["teambrmgvi"]
name = "MG, Vicosa"

[[sedes]]
codes = ["teambrbasa"]
name = "BA, Salvador"

[[sedes]]
codes = ["teambracrb"]
name = "AC, Rio Branco"

[[sedes]]
codes = ["teambralma"]
name = "AL, Maceio"

[[sedes]]
codes = ["teambrmasl"]
name = "MA, Sao Luis"

[[sedes]]
codes = ["teambramma"]
name = "AM, Manaus"

[[sedes]]
codes = ["teambrrnna"]
name = "RN, Natal"

[[sedes]]
codes = ["teambrmsdo"]
name = "MS, Dourados"

[[sedes]]
codes = ["teambrmtsi"]
name = "MT, Sinop"

[[sedes]]
codes = ["teambrtopa"]
name = "TO, Palmas"

[[sedes]]
codes = ["teambrscjo"]
name = "SC, Joinville"

[[sedes]]
codes = ["teambrmtaa"]
name = "MT, Alto Araguaia"

[[sedes]]
codes = ["teambrpaor"]
name = "PA, Oriximina"

[[sedes]]
codes = ["teambrspsc"]
name = "SP, Sao Carlos"
