[titulo]
name = "CCL"
codes = ["ccl"]

[[sedes]]
codes = ["ccl"]
name = "CCL"

[[sedes]]
codes = ["brccl"]
name = "CCL Brasil"

[[sedes]]
name = "CCL Brasil"
codes = ["boccl"]


[[sedes]]
codes = ["caccl"]
name = "CCL Centro America"
