[titulo]
name = "CCL"
codes = ["ccl"]

[[sedes]]
codes = ["ccl"]
name = "CCL"

[[sedes]]
name = "CCL Brasil"
codes = ["brccl"]

[[sedes]]
name = "CCL Bolivia"
codes = ["boccl"]

[[sedes]]
codes = ["caccl"]
name = "CCL Centro America"
