[titulo]
name = "Centro America"
codes = ["teamca"]

[[sedes]]
codes = [
  "caurlq23",
  "caufla23",
  "cacrsp23",
  "caujsc23",
  "cananm23",
  "catcrs23",
  "caucrp23",
  "cauncn23",
  "caunco23",
  "catcrl23",
  "caumgg23",
  "catcra23",
]
name = "Centro America"

[[sedes]]
codes = ["caurlq23"]
name = "Universidad Rafael Landívar sede Quetzaltenango"

[[sedes]]
codes = ["caufla23"]
name = "Universidad Rafael Landívar"

[[sedes]]
codes = ["cacrsp23"]
name = "Universidad de Costa Rica sede San Pedro"

[[sedes]]
codes = ["caujsc23"]
name = "Universidad Centroamericana José Simeón Cañas"

[[sedes]]
codes = ["cananm23"]
name = "Universidad Nacional Autónoma de Nicaragua sede Managua"

[[sedes]]
codes = ["catcrs23"]
name = "Tecnológico de Costa Rica Sede Cartago"

[[sedes]]
codes = ["caucrp23"]
name = "Universidad de Costa Rica Pacífico"

[[sedes]]
codes = ["cauncn23"]
name = "Universidad Nacional Chorotega - Nicoya"

[[sedes]]
codes = ["caunco23"]
name = "Universidad Nacional sede Coto"

[[sedes]]
codes = ["catcrl23"]
name = "Tecnológico de Costa Rica sede Limón"

[[sedes]]
codes = ["caumgg23"]
name = "Universidad Mariano Galvez de Guatemala Campus Chiquimulilla"

[[sedes]]
codes = ["catcra23"]
name = "Tecnológico de Costa Rica Sede Alajuela"
