[titulo]
name = "Centro America"
codes = ["teamca"]

[[sedes]]
codes = ["teamca"]
name = "Centro America"

[[sedes]]
codes = ["caurlq"]
name = "Universidad Rafael Landívar sede Quetzaltenango"

[[sedes]]
codes = ["caufla"]
name = "Universidad Rafael Landívar"

[[sedes]]
codes = ["cacrsp"]
name = "Universidad de Costa Rica sede San Pedro"

[[sedes]]
codes = ["caujsc"]
name = "Universidad Centroamericana José Simeón Cañas"

[[sedes]]
codes = ["cananm"]
name = "Universidad Nacional Autónoma de Nicaragua sede Managua"

[[sedes]]
codes = ["catcrs"]
name = "Tecnológico de Costa Rica Sede Cartago"

[[sedes]]
codes = ["caucrp"]
name = "Universidad de Costa Rica Pacífico"

[[sedes]]
codes = ["cauncn"]
name = "Universidad Nacional Chorotega - Nicoya"

[[sedes]]
codes = ["caunco"]
name = "Universidad Nacional sede Coto"

[[sedes]]
codes = ["catcrl"]
name = "Tecnológico de Costa Rica sede Limón"

[[sedes]]
codes = ["caumgg"]
name = "Universidad Mariano Galvez de Guatemala Campus Chiquimulilla"

[[sedes]]
codes = ["catcra"]
name = "Tecnológico de Costa Rica Sede Alajuela"
