[titulo]
name = "Centro America"
codes = ["teamca"]

[[sedes]]
codes = ["teamca"]
name = "Centro America"

[[sedes]]
codes = ["24cacral"]
name = "Tecnológico de Costa Rica Sede Alajuela"

[[sedes]]
name = 'Universidad Centroamericana "José Simeón Cañas"'
codes = ["24cacejc"]

[[sedes]]
codes = ["24cacrsp"]
name = "Universidad de Costa Rica sede San Pedro"

[[sedes]]
codes = ["24caunrl"]
name = "Universidad Rafael Landívar"

[[sedes]]
codes = ["24caurlq"]
name = "Universidad Rafael Landívar sede Quetzaltenango"

[[sedes]]
codes = ["24caunfg"]
name = "Universidad Francisco Gavidia"

[[sedes]]
codes = ["24caundb"]
name = "Universidad Don Bosco"

[[sedes]]
codes = ["24caunor"]
name = "Universidad de Oriente"

[[sedes]]
codes = ["24caunga"]
name = "Universidad Galileo"

[[sedes]]
codes = ["24cavagt"]
name = "Universidad del Valle GT"

[[sedes]]
codes = ["24caitgu"]
name = "Universidad del Itsmo de Guatemala"
