[titulo]
name = "Chile"
codes = ["teamch"]

# CHILE
[[sedes]]
name = "Chile"
codes = ["chsaud23", "chrauo23", "chcouc23", "chsaut23", "chcoud23", "chtauc23"]

[[sedes]]
codes = ["chsaud23"]
name = "Santiago (UDP)"

[[sedes]]
codes = ["chrauo23"]
name = "Rancagua (UOH)"

[[sedes]]
codes = ["chcouc23"]
name = "Coquimbo / La Serena (UCN)"

[[sedes]]
codes = ["chsaut23"]
name = "Santiago (UTFSM)"

[[sedes]]
codes = ["chcoud23"]
name = "Concepción (UdeC)"

[[sedes]]
codes = ["chtauc23"]
name = "Talca (UCM)"
