[titulo]
name = "Chile"
codes = ["teamch"]

# CHILE
[[sedes]]
name = "Chile"
codes = ["teamch"]

[[sedes]]
codes = ["chsaud"]
name = "Santiago (UDP)"

[[sedes]]
codes = ["chrauo"]
name = "Rancagua (UOH)"

[[sedes]]
codes = ["chcouc"]
name = "Coquimbo / La Serena (UCN)"

[[sedes]]
codes = ["chsaut"]
name = "Santiago (UTFSM)"

[[sedes]]
codes = ["chcoud"]
name = "Concepción (UdeC)"

[[sedes]]
codes = ["chtauc"]
name = "Talca (UCM)"
