[titulo]
name = "Latin America"
codes = [""]
ouro = 1
prata = 2
bronze = 3

[[sedes]]
name = "Brasil"
codes = ["teambr"]
ouro = 4
prata = 8
bronze = 12

[[sedes]]
name = "Bolivia"
codes = ["teamsobo"]

[[sedes]]
name = "Chile"
codes = ["teamch"]

[[sedes]]
codes = ["teammx"]
name = "Mexico"

[[sedes]]
codes = ["teamca"]
name = "Centro America"
