[titulo]
name = "Mexico"
codes = ["teammx"]

# MEXICO
[[sedes]]
codes = [
  "mxitrr",
  "mxitcx",
  "mxitza",
  "mxitzo",
  "mxitpu",
  "mxtnml",
  "mxicul",
  "mxitrv",
  "mxitsz",
  "mxitsv",
  "mxitoh",
  "mxitoc",
  "mxitph",
  "mxitck",
  "mxitcm",
  "mxitpz",
  "mxitch",
  "mxitox",
  "mxitco",
  "mxuayc",
  "mxitpn",
  "mxitnl",
  "mxitcl",
  "mxitap",
  "mxitcn",
  "mxitmo",
  "mxitcz",
  "mxithe",
  "mxitur",
  "mxitcj",
  "mxitsg",
  "mxuasi",
  "mxiver",
  "mximan",
  "mxitlr",
  "mxlzcr",
  "mxisur",
  "mxitlg",
  "mxuacj",
  "mxuton",
  "mxucos",
  "mxnmig",
  "mxnmci",
  "mxcipn",
  "mxuoax",
  "mxupab",
  "mxupag",
  "mxumor",
  "mxtmcv",
  "mxcnnu",
  "mxcuat",
  "mxuval",
  "mxupub",
  "mxucei",
  "mxcuaz",
  "mxslpt",
  "mxuanl",
  "mxttol",
  "mxtmcp",
  "mxmont",
  "mxtmem",
  "mxuaeh",
  "mxugnj",
  "mxomif",
  "mxuach",
  "mxsujs",
  "mxuaag",
  "mxmari",
  "mxtmmx",
  "mxumsn",
  "mxuayt",
  "mxumon",
  "mxfims",
  "mxquer",
]
name = "Mexico"

[[sedes]]
codes = ["mxitrr"]
name = "Instituto Tecnológico de Parral"

[[sedes]]
codes = ["mxitcx"]
name = "Instituto Tecnológico Superior de Comalcaco"

[[sedes]]
codes = ["mxitza"]
name = "Instituto Tecnológico de Zacatepec"

[[sedes]]
codes = ["mxitzo"]
name = "Instituto Tecnológico Superior de Zongolica"

[[sedes]]
codes = ["mxitpu"]
name = "Instituto Tecnológico Superior de Purísima del Rincón"

[[sedes]]
codes = ["mxtnml"]
name = "Instituto Tecnológico de León"

[[sedes]]
codes = ["mxicul"]
name = "Instituto Tecnológico de Culiacán"

[[sedes]]
codes = ["mxitrv"]
name = "Instituto Tecnológico Superior de Rioverde"

[[sedes]]
codes = ["mxitsz"]
name = "Instituto Tecnológico y de Estudios Superiores de Zamora"

[[sedes]]
codes = ["mxitsv"]
name = "Instituto Tecnológico Superior de Salvatierra"

[[sedes]]
codes = ["mxitoh"]
name = "Instituto Tecnológico Superior del Oriente del Estado de Hidalgo"

[[sedes]]
codes = ["mxitoc"]
name = "Instituto Tecnologico Superior del Occidente del Estado de Hidalgo"

[[sedes]]
codes = ["mxitph"]
name = "Instituto Tecnológico de Pachuca"

[[sedes]]
codes = ["mxitck"]
name = "Instituto Tecnológico Superior de Calkiní"

[[sedes]]
codes = ["mxitcm"]
name = "Instituto Tecnológico de Ciudad Madero"

[[sedes]]
codes = ["mxitpz"]
name = "Instituto Tecnológico Superior de Pátzcuaro"

[[sedes]]
codes = ["mxitch"]
name = "Instituto Tecnológico Superior de Ciudad Hidalgo"

[[sedes]]
codes = ["mxitox"]
name = "Instituto Tecnológico de Oaxaca"

[[sedes]]
codes = ["mxitco"]
name = "Instituto Tecnológico de Comitán"

[[sedes]]
codes = ["mxuayc"]
name = "Universidad Autónoma de Yucatán"

[[sedes]]
codes = ["mxitpn"]
name = "Instituto Tecnológico de Piedras Negras"

[[sedes]]
codes = ["mxitnl"]
name = "Instituto Tecnológico de Nuevo León"

[[sedes]]
codes = ["mxitcl"]
name = "Instituto Tecnológico de Celaya"

[[sedes]]
codes = ["mxitap"]
name = "Instituto Tecnológico Superior de Apatzingán"

[[sedes]]
codes = ["mxitcn"]
name = "Instituto Tecnológico de Cancún"

[[sedes]]
codes = ["mxitmo"]
name = "Instituto Tecnológico de Morelia"

[[sedes]]
codes = ["mxitcz"]
name = "Instituto Tecnológico Superior de Coatzacoalcos"

[[sedes]]
codes = ["mxithe"]
name = "Instituto Tecnológico Superior de Huetamo"

[[sedes]]
codes = ["mxitur"]
name = "Instituto Tecnológico Superior de Uruapan"

[[sedes]]
codes = ["mxitcj"]
name = "Instituto Tecnológico de Ciudad Juárez"

[[sedes]]
codes = ["mxitsg"]
name = "ACM Campus ITESG"

[[sedes]]
codes = ["mxuasi"]
name = "Coding CUP Sinaloa"

[[sedes]]
codes = ["mxiver"]
name = "Comunidad Estudiantil de Programación Competitiva de Instituto Tecnológico de Veracruz"

[[sedes]]
codes = ["mximan"]
name = "Sistemas Computacionales ITS Mante"

[[sedes]]
codes = ["mxitlr"]
name = "ACM ICPC Algorithmia ITSLerdo"

[[sedes]]
codes = ["mxlzcr"]
name = "Programación Lázaro Cárdenas"

[[sedes]]
codes = ["mxisur"]
name = "Coding CUP ITSUR"
[[sedes]]
codes = ["mxitlg"]
name = "Club de Programación Competitiva ITLag"

[[sedes]]
codes = ["mxuacj"]
name = "UACJ Algorithmic Club"

[[sedes]]
codes = ["mxuton"]
name = "Universidad de Guadalajara CUTonalá"

[[sedes]]
codes = ["mxucos"]
name = "Universidad de Guadalajara CUCOSTA"

[[sedes]]
codes = ["mxnmig"]
name = "UNAM Facultad de Ingeniería - Club de Programación Competitiva"

[[sedes]]
codes = ["mxnmci"]
name = "UNAM Facultad de Ciencias - Club de Programación Competitiva"

[[sedes]]
codes = ["mxcipn"]
name = "Red Académica de Programación Competitiva del Instituto Politécnico Nacional / UNAM FES Acatlán / UAM / ITAM"

[[sedes]]
codes = ["mxuoax"]
name = "Universidad Anahuac Oaxaca"

[[sedes]]
codes = ["mxupab"]
name = "Universidad Panamericana Campus Bonaterra"

[[sedes]]
codes = ["mxupag"]
name = "Universidad Panamericana Campus Guadalajara"

[[sedes]]
codes = ["mxumor"]
name = "Escuela Nacional de Estudios Superiores UNAM Campus Morelia"

[[sedes]]
codes = ["mxtmcv"]
name = "Tecnologico de Monterrey Cuernavaca"

[[sedes]]
codes = ["mxcnnu"]
name = "Centro de Nanociencias y Nanotecnologia UNAM"

[[sedes]]
codes = ["mxcuat"]
name = "Capitulo Estudiantil UAT ACM"

[[sedes]]
codes = ["mxuval"]
name = "Club de Algoritmia CUValles"

[[sedes]]
codes = ["mxupub"]
name = "CPU - Programación Competitiva Universidad Popular Autónoma del Estado de Puebla"

[[sedes]]
codes = ["mxucei"]
name = "CAC - Club de Algoritmia CUCEI"

[[sedes]]
codes = ["mxcuaz"]
name = "Club de Programación Competitiva UAZ"

[[sedes]]
codes = ["mxslpt"]
name = "ICPC San Luis Potosi"

[[sedes]]
codes = ["mxuanl"]
name = "ACM Universidad Autonoma de Nuevo Leon"

[[sedes]]
codes = ["mxttol"]
name = "Programación Competitiva Tec Toluca"

[[sedes]]
codes = ["mxtmcp"]
name = "Programación Competitiva Tec de Monterrey Puebla"

[[sedes]]
codes = ["mxmont"]
name = "ACM Monterrey"

[[sedes]]
codes = ["mxtmem"]
name = "Programación Competitiva Tec de Monterrey Campus Estado de México"

[[sedes]]
codes = ["mxuaeh"]
name = "Universidad Autónoma del Estado de Hidalgo"

[[sedes]]
codes = ["mxugnj"]
name = "Universidad de Guanajuato"

[[sedes]]
codes = ["mxomif"]
name = "Olimpiada Mexicana de Informatica"

[[sedes]]
codes = ["mxuach"]
name = "Universidad Autonoma de Chihuahua"

[[sedes]]
codes = ["mxsujs"]
name = "Sistema Universitario Jesuita"

[[sedes]]
codes = ["mxuaag"]
name = "Universidad Autonoma de Aguascalientes"

[[sedes]]
codes = ["mxmari"]
name = "Universidad Marista de Guadalajara"

[[sedes]]
codes = ["mxtmmx"]
name = "Tecnológico de Monterrey Campus Ciudad de México"

[[sedes]]
codes = ["mxumsn"]
name = "Universidad Michoacana de San Nicolás de Hidalgo"

[[sedes]]
codes = ["mxuayt"]
name = "Universidad Autónoma de Yucatan Unidad Multidisciplinaria Tizimín"

[[sedes]]
codes = ["mxumon"]
name = "Universidad de Monterrey"

[[sedes]]
codes = ["mxfims"]
name = "Facultad de Informática Mazatlán Universidad Autónoma de Sinaloa"

[[sedes]]
codes = ["mxquer"]
name = "ACM Querétaro"
