[[secrets]]
name = "Brasil"
secret = "Brasil"

[[secrets]]
name = "Chile"
secret = "Chile"

[[secrets]]
name = "Mexico"
secret = "Mexico"

[[secrets]]
name = "Bolivia"
secret = "Bolivia"

[[secrets]]
name = "Centro America"
secret = "Centro"

[[secrets]]
name = "CCLBrasil"
secret = "CCLBrasil"

[[secrets]]
name = "CCLBolivia"
secret = "CCLBolivia"

[[secrets]]
name = "Supersede Norte"
secret = "Supersede Norte"

[[secrets]]
name = "Supersede Nordeste"
secret = "Supersede Nordeste"

[[secrets]]
name = "Supersede Centro Oeste"
secret = "Supersede Centro Oeste"

[[secrets]]
name = "Supersede Sul"
secret = "Supersede Sul"

[[secrets]]
name = "Supersede Minas"
secret = "Supersede Minas"

[[secrets]]
name = "Supersede Parana"
secret = "Supersede Parana"

[[secrets]]
name = "Supersede RN"
secret = "Supersede RN"

[[secrets]]
name = "Supersede Sao Paulo"
secret = "Supersede Sao Paulo"

[[secrets]]
name = "Campo Grande"
secret = "Campo Grande"

[[secrets]]
name = "Itaituba"
secret = "Itaituba"

[[secrets]]
name = "Cuiabá"
secret = "Cuiabá"

[[secrets]]
name = "Brasília"
secret = "Brasília"

[[secrets]]
name = "Olinda"
secret = "Olinda"

[[secrets]]
name = "São Cristóvão"
secret = "São Cristóvão"

[[secrets]]
name = "São Luís"
secret = "São Luís"

[[secrets]]
name = "Teresina"
secret = "Teresina"

[[secrets]]
name = "Juazeiro do Norte"
secret = "Juazeiro do Norte"

[[secrets]]
name = "Campina Grande"
secret = "Campina Grande"

[[secrets]]
name = "Natal"
secret = "Natal"

[[secrets]]
name = "Balsas"
secret = "Balsas"

[[secrets]]
name = "Juazeiro"
secret = "Juazeiro"

[[secrets]]
name = "Fortaleza"
secret = "Fortaleza"

[[secrets]]
name = "Salvador"
secret = "Salvador"

[[secrets]]
name = "Pau dos Ferros"
secret = "Pau dos Ferros"

[[secrets]]
name = "Maceió"
secret = "Maceió"

[[secrets]]
name = "Quixadá"
secret = "Quixadá"

[[secrets]]
name = "Rio Branco"
secret = "Rio Branco"

[[secrets]]
name = "Paragominas"
secret = "Paragominas"

[[secrets]]
name = "Porto Velho"
secret = "Porto Velho"

[[secrets]]
name = "Manaus"
secret = "Manaus"

[[secrets]]
name = "Montes Claros"
secret = "Montes Claros"

[[secrets]]
name = "Timóteo"
secret = "Timóteo"

[[secrets]]
name = "Bauru"
secret = "Bauru"

[[secrets]]
name = "Taubaté"
secret = "Taubaté"

[[secrets]]
name = "São João del-Rei"
secret = "São João del-Rei"

[[secrets]]
name = "Belo Horizonte"
secret = "Belo Horizonte"

[[secrets]]
name = "Sorocaba"
secret = "Sorocaba"

[[secrets]]
name = "Uberlândia"
secret = "Uberlândia"

[[secrets]]
name = "Barretos"
secret = "Barretos"

[[secrets]]
name = "Rio de Janeiro"
secret = "Rio de Janeiro"

[[secrets]]
name = "São Paulo"
secret = "São Paulo"

[[secrets]]
name = "Uberaba"
secret = "Uberaba"

[[secrets]]
name = "Santa Rita do Sapucaí"
secret = "Santa Rita do Sapucaí"

[[secrets]]
name = "Viçosa"
secret = "Viçosa"

[[secrets]]
name = "Florianópolis"
secret = "Florianópolis"

[[secrets]]
name = "Campo Mourão"
secret = "Campo Mourão"

[[secrets]]
name = "Curitiba"
secret = "Curitiba"

[[secrets]]
name = "Chapecó"
secret = "Chapecó"

[[secrets]]
name = "Ijuí"
secret = "Ijuí"

[[secrets]]
name = "Toledo"
secret = "Toledo"

[[secrets]]
name = "Porto Alegre"
secret = "Porto Alegre"
