[[secrets]]
name = "Brasil"
secret = "Brasil"

[[secrets]]
name = "Mexico"
secret = "Mexico"

[[secrets]]
name = "Bolivia"
secret = "Bolivia"

[[secrets]]
name = "Centro America"
secret = "Centro"

[[secrets]]
name = "CCL"
secret = "CCL"

[[secrets]]
name = "Brasil CCL"
secret = "Brasil CCL"

[[secrets]]
name = "Bolivia CCL"
secret = "Bolivia CCL"
