[titulo]
name = "Brasil"
codes = ["teambr"]
ouro = 4
prata = 8
bronze = 12


[[sedes]]
name = "Brasil"
codes = ["teambr"]
ouro = 4
prata = 8
bronze = 12

[[sedes]]
name = "Norte"
codes = ["bracrb", "bramma", "brapmc", "brpabe", "brpama", "brpasa", "brropv", "brrrbv"]

[[sedes]]
name = "Sul"
codes = ["brprcm", "brprcu", "brprfi", "brrspe", "brrspf", "brscfl", "brscpi"]

[[sedes]]
name = "Centro-Oeste"
codes = ["brdfdf", "brgogo", "brmscg", "brmsdo", "brmtcu"]

[[sedes]]
name = "Sudeste"
codes = ["bresse", "brmgbe", "brmgit", "brmgmc", "brmgpa", "brmgsj", "brmgti", "brmgub", "brmgud", "brmgvi", "brrjrj", "brspma", "brsprp", "brspsj", "brspso", "brspsp"]

[[sedes]]
name = "Nordeste"
codes = ["bralma", "brbagu", "brbaju", "brbasa", "brcecr", "brcefo", "brcejn", "brceqx", "brceti", "brmaba", "brmasl", "brpbcg", "brpere", "brpite", "brrnna", "brrnpf", "brsesc"]

[[sedes]]
name = "AC"
codes = ["brac"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "AL"
codes = ["bral"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "AM"
codes = ["bram"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "AP"
codes = ["brap"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "BA"
codes = ["brba"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "CE"
codes = ["brce"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "DF"
codes = ["brdf"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "ES"
codes = ["bres"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "GO"
codes = ["brgo"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "MA"
codes = ["brma"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "MG"
codes = ["brmg"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "MS"
codes = ["brms"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "MT"
codes = ["brmt"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "PA"
codes = ["brpa"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "PB"
codes = ["brpb"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "PE"
codes = ["brpe"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "PI"
codes = ["brpi"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "PR"
codes = ["brpr"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "RJ"
codes = ["brrj"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "RN"
codes = ["brrn"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "RO"
codes = ["brro"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "RR"
codes = ["brrr"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "RS"
codes = ["brrs"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "SC"
codes = ["brsc"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "SE"
codes = ["brse"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "SP"
codes = ["brsp"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "Supersede estadual do Ceará"
codes = ["brcecr", "brcefo", "brcejn", "brceqx"]
ouro = 2
prata = 0
bronze = 0

[[sedes]]
name = "Supersede estadual de Minas Gerais"
codes = ["brmgmc", "brmgpa", "brmgti", "brmgud"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "Supersede estadual do Rio Grande do Norte"
codes = ["brrnna", "brrnpf"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "Supersede da região Norte"
codes = ["bracrb", "bramma", "brapmc", "brropv", "brrrbv"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "Supersede da região Nordeste"
codes = ["bralma", "brbagu", "brbaju", "brmaba", "brmasl", "brpbcg", "brpere", "brpite", "brsesc"]
ouro = 4
prata = 0
bronze = 0

[[sedes]]
name = "Supersede da região Sul"
codes = ["brprcm", "brscfl"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "Supersede Brasil"
codes = ["brmscg", "brmsdo", "brmtcu"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "DF, Brasília"
codes = ["brdfdf"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "GO, Goiânia"
codes = ["brgogo"]
ouro = 2
prata = 0
bronze = 0

[[sedes]]
name = "MS, Campo Grande"
codes = ["brmscg"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "MS, Dourados"
codes = ["brmsdo"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "MT, Cuiabá"
codes = ["brmtcu"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "AL, Maceió"
codes = ["bralma"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "BA, Guanambi"
codes = ["brbagu"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "BA, Juazeiro"
codes = ["brbaju"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "BA, Salvador"
codes = ["brbasa"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "CE, Crateús"
codes = ["brcecr"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "CE, Fortaleza"
codes = ["brcefo"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "CE, Juazeiro do Norte"
codes = ["brcejn"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "CE, Quixadá"
codes = ["brceqx"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "CE, Tianguá"
codes = ["brceti"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "MA, Balsas"
codes = ["brmaba"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "MA, São Luis"
codes = ["brmasl"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "PB, Campina Grande"
codes = ["brpbcg"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "PE, Recife"
codes = ["brpere"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "PI, Teresina"
codes = ["brpite"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "RN, Natal"
codes = ["brrnna"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "RN, Pau dos Ferros"
codes = ["brrnpf"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "SE, São Cristóvão"
codes = ["brsesc"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "AC, Rio Branco"
codes = ["bracrb"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "AM, Manaus"
codes = ["bramma"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "AP, Macapá"
codes = ["brapmc"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "PA, Belém"
codes = ["brpabe"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "PA, Marabá"
codes = ["brpama"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "PA, Santarém"
codes = ["brpasa"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "RO, Porto Velho"
codes = ["brropv"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "RR, Boa Vista"
codes = ["brrrbv"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "ES, Serra"
codes = ["bresse"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "MG, Belo Horizonte"
codes = ["brmgbe"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "MG, Itajubá"
codes = ["brmgit"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "MG, Montes Claros"
codes = ["brmgmc"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "MG, Paracatu"
codes = ["brmgpa"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "MG, São João del Rei"
codes = ["brmgsj"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "MG, Timóteo"
codes = ["brmgti"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "MG, Uberaba"
codes = ["brmgub"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "MG, Uberlândia"
codes = ["brmgud"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "MG, Viçosa"
codes = ["brmgvi"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "RJ, Rio de Janeiro"
codes = ["brrjrj"]
ouro = 2
prata = 0
bronze = 0

[[sedes]]
name = "SP, Marília"
codes = ["brspma"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "SP, Ribeirão Preto"
codes = ["brsprp"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "SP, São José dos Campos"
codes = ["brspsj"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "SP, Sorocaba"
codes = ["brspso"]
ouro = 2
prata = 0
bronze = 0

[[sedes]]
name = "SP, São Paulo"
codes = ["brspsp"]
ouro = 3
prata = 0
bronze = 0

[[sedes]]
name = "PR, Campo Mourão"
codes = ["brprcm"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "PR, Curitiba"
codes = ["brprcu"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "PR, Foz do Iguaçu"
codes = ["brprfi"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "RS, Pelotas"
codes = ["brrspe"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "RS, Passo Fundo"
codes = ["brrspf"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "SC, Florianópolis"
codes = ["brscfl"]
ouro = 0
prata = 0
bronze = 0

[[sedes]]
name = "SC, Pinhalzinho"
codes = ["brscpi"]
ouro = 1
prata = 0
bronze = 0

[[sedes]]
name = "Times femininos - 3 competidoras"
codes = ["^(teambralma009|teambramma001|teambrbagu005|teambrbasa008|teambrbasa020|teambrcecr006|teambrcefo007|teambrcejn002|teambrdfdf007|teambrdfdf008|teambrdfdf015|teambresse008|teambrgogo002|teambrgogo017|teambrgogo024|teambrgogo036|teambrgogo038|teambrgogo041|teambrmgbe009|teambrmgbe011|teambrmgbe013|teambrmgbe021|teambrmgbe023|teambrmgbe026|teambrmgbe033|teambrmgbe035|teambrmgbe036|teambrmgit025|teambrmgsj008|teambrmgsj012|teambrmgsj013|teambrmgsj014|teambrmgsj019|teambrmgti005|teambrmgub006|teambrmgub021|teambrmgud007|teambrmgud008|teambrmgvi009|teambrmgvi010|teambrmgvi013|teambrmscg003|teambrmscg005|teambrmscg007|teambrmtcu006|teambrpabe001|teambrpabe005|teambrpabe015|teambrpabe024|teambrpama008|teambrpasa001|teambrpasa005|teambrpbcg014|teambrpere006|teambrpere007|teambrpere010|teambrprcm015|teambrprcm016|teambrprcu005|teambrprcu011|teambrprcu021|teambrprcu026|teambrrjrj008|teambrrjrj009|teambrrjrj010|teambrrjrj012|teambrrnpf014|teambrscfl005|teambrscpi007|teambrscpi014|teambrsesc003|teambrspma016|teambrsprp016|teambrspsj022|teambrspso028|teambrspso041|teambrspsp033|teambrspsp043)$"]

[[sedes]]
name = "Times femininos - 2 competidoras"
codes = ["^(teambramma011|teambrbasa013|teambrcecr008|teambrcecr014|teambrceqx003|teambrceqx009|teambrdfdf018|teambrdfdf020|teambrdfdf023|teambresse009|teambresse011|teambrgogo004|teambrgogo018|teambrmgbe004|teambrmgbe019|teambrmgbe028|teambrmgit019|teambrmgsj010|teambrmgsj023|teambrmgsj024|teambrmgub009|teambrmgub014|teambrmgub018|teambrmgvi002|teambrmgvi018|teambrmscg010|teambrmscg012|teambrmtcu007|teambrpabe007|teambrpama006|teambrpasa006|teambrpasa009|teambrpite002|teambrprcu020|teambrprfi017|teambrprfi019|teambrrjrj014|teambrrjrj040|teambrrnna004|teambrrnpf001|teambrrspe003|teambrrspe011|teambrrspe019|teambrrspf002|teambrrspf005|teambrrspf007|teambrrspf015|teambrscpi006|teambrscpi008|teambrspma002|teambrspma014|teambrsprp006|teambrspsj015|teambrspsj029|teambrspsp018|teambrspsp036)$"]

[[sedes]]
name = "Times femininos - 1 competidora"
codes = ["^(teambracrb002|teambralma002|teambralma005|teambralma007|teambramma002|teambramma003|teambramma004|teambramma007|teambramma009|teambramma010|teambrapmc009|teambrbagu006|teambrbaju003|teambrbasa011|teambrbasa014|teambrbasa015|teambrbasa016|teambrbasa019|teambrcecr004|teambrcecr009|teambrcecr011|teambrcecr013|teambrcefo003|teambrcefo008|teambrcefo013|teambrcefo014|teambrcefo016|teambrcefo017|teambrcejn006|teambrcejn010|teambrcejn012|teambrceqx002|teambrceqx005|teambrceqx013|teambrceti001|teambrceti005|teambrceti010|teambrceti011|teambrdfdf011|teambrdfdf012|teambrdfdf016|teambrgogo009|teambrgogo015|teambrgogo020|teambrgogo027|teambrgogo040|teambrmasl001|teambrmasl002|teambrmasl004|teambrmasl005|teambrmgbe002|teambrmgbe005|teambrmgbe006|teambrmgbe010|teambrmgbe012|teambrmgbe017|teambrmgbe020|teambrmgbe022|teambrmgbe032|teambrmgbe034|teambrmgit001|teambrmgit010|teambrmgit013|teambrmgit015|teambrmgit020|teambrmgit022|teambrmgit026|teambrmgmc002|teambrmgmc004|teambrmgsj004|teambrmgsj016|teambrmgub005|teambrmgub016|teambrmgub020|teambrmgud006|teambrmgud009|teambrmgud011|teambrmgud012|teambrmgud013|teambrmgvi019|teambrmscg002|teambrmscg004|teambrmsdo002|teambrmsdo003|teambrmtcu008|teambrpabe002|teambrpabe013|teambrpabe018|teambrpama001|teambrpama004|teambrpama005|teambrpasa003|teambrpasa010|teambrpbcg006|teambrpbcg013|teambrpere004|teambrpere013|teambrpite001|teambrpite007|teambrprcm002|teambrprcm003|teambrprcm005|teambrprcm006|teambrprcm009|teambrprcm013|teambrprcm017|teambrprcu006|teambrprcu012|teambrprcu014|teambrprcu032|teambrprcu037|teambrprfi004|teambrprfi009|teambrprfi012|teambrprfi021|teambrprfi024|teambrrjrj005|teambrrjrj013|teambrrjrj015|teambrrjrj028|teambrrjrj039|teambrrnna001|teambrrnna003|teambrrnna008|teambrrnna010|teambrrnna012|teambrrnna014|teambrrnna017|teambrrnna018|teambrrnna021|teambrrnpf007|teambrrnpf008|teambrrnpf011|teambrrnpf012|teambrrnpf015|teambrrnpf017|teambrrspe020|teambrrspf008|teambrrspf014|teambrrspf019|teambrrspf026|teambrrspf032|teambrrspf035|teambrrspf040|teambrrspf043|teambrscfl003|teambrscfl008|teambrscfl013|teambrscpi003|teambrscpi004|teambrscpi005|teambrscpi009|teambrscpi015|teambrsesc004|teambrsesc005|teambrsesc008|teambrsesc013|teambrsesc014|teambrspma004|teambrspma006|teambrspma011|teambrspma024|teambrsprp010|teambrsprp011|teambrsprp019|teambrspsj009|teambrspsj010|teambrspsj017|teambrspsj020|teambrspsj021|teambrspso003|teambrspso014|teambrspso044|teambrspsp002|teambrspsp008|teambrspsp010|teambrspsp011|teambrspsp017|teambrspsp025|teambrspsp027|teambrspsp028|teambrspsp035|teambrspsp040|teambrspsp041|teambrspsp042|teambrspsp044|teambrspsp049|teambrspsp050)$"]
