[titulo]
name = "Brasil"
codes = ["teambr"]
ouro = 4
prata = 8
bronze = 12

[[sedes]]
name = "Brasil"
codes = ["teambr"]
ouro = 4
prata = 8
bronze = 12

[[sedes]]
name = "DF, Brasília"
codes = ["brdfdf"]

[[sedes]]
name = "GO, Goiânia"
codes = ["brgogo"]

[[sedes]]
name = "MS, Campo Grande"
codes = ["brmscg"]

[[sedes]]
name = "MS, Dourados"
codes = ["brmsdo"]

[[sedes]]
name = "MT, Cuiabá"
codes = ["brmtcu"]

[[sedes]]
name = "AL, Maceió"
codes = ["bralma"]

[[sedes]]
name = "BA, Guanambi"
codes = ["brbagu"]

[[sedes]]
name = "BA, Juazeiro"
codes = ["brbaju"]

[[sedes]]
name = "BA, Salvador"
codes = ["brbasa"]

[[sedes]]
name = "CE, Crateús"
codes = ["brcecr"]

[[sedes]]
name = "CE, Fortaleza"
codes = ["brcefo"]

[[sedes]]
name = "CE, Juazeiro do Norte"
codes = ["brcejn"]

[[sedes]]
name = "CE, Quixadá"
codes = ["brceqx"]

[[sedes]]
name = "CE, Tianguá"
codes = ["brceti"]

[[sedes]]
name = "MA, Balsas"
codes = ["brmaba"]

[[sedes]]
name = "MA, São Luis"
codes = ["brmasl"]

[[sedes]]
name = "PB, Campina Grande"
codes = ["brpbcg"]

[[sedes]]
name = "PE, Recife"
codes = ["brpere"]

[[sedes]]
name = "PI, Teresina"
codes = ["brpite"]

[[sedes]]
name = "RN, Natal"
codes = ["brrnna"]

[[sedes]]
name = "RN, Pau dos Ferros"
codes = ["brrnpf"]

[[sedes]]
name = "SE, São Cristóvão"
codes = ["brsesc"]

[[sedes]]
name = "AC, Rio Branco"
codes = ["bracrb"]

[[sedes]]
name = "AM, Manaus"
codes = ["bramma"]

[[sedes]]
name = "AP, Macapá"
codes = ["brapmc"]

[[sedes]]
name = "PA, Belém"
codes = ["brpabe"]

[[sedes]]
name = "PA, Marabá"
codes = ["brpama"]

[[sedes]]
name = "PA, Santarém"
codes = ["brpasa"]

[[sedes]]
name = "RO, Porto Velho"
codes = ["brropv"]

[[sedes]]
name = "RR, Boa Vista"
codes = ["brrrbv"]

[[sedes]]
name = "ES, Serra"
codes = ["bresse"]

[[sedes]]
name = "MG, Belo Horizonte"
codes = ["brmgbe"]

[[sedes]]
name = "MG, Itajubá"
codes = ["brmgit"]

[[sedes]]
name = "MG, Montes Claros"
codes = ["brmgmc"]

[[sedes]]
name = "MG, Paracatu"
codes = ["brmgpa"]

[[sedes]]
name = "MG, São João del Rei"
codes = ["brmgsj"]

[[sedes]]
name = "MG, Timóteo"
codes = ["brmgti"]

[[sedes]]
name = "MG, Uberaba"
codes = ["brmgub"]

[[sedes]]
name = "MG, Uberlândia"
codes = ["brmgud"]

[[sedes]]
name = "MG, Viçosa"
codes = ["brmgvi"]

[[sedes]]
name = "RJ, Rio de Janeiro"
codes = ["brrjrj"]

[[sedes]]
name = "SP, Marília"
codes = ["brspma"]

[[sedes]]
name = "SP, Ribeirão Preto"
codes = ["brsprp"]

[[sedes]]
name = "SP, São José dos Campos"
codes = ["brspsj"]

[[sedes]]
name = "SP, Sorocaba"
codes = ["brspso"]

[[sedes]]
name = "SP, São Paulo"
codes = ["brspsp"]

[[sedes]]
name = "PR, Campo Mourão"
codes = ["brprcm"]

[[sedes]]
name = "PR, Curitiba"
codes = ["brprcu"]

[[sedes]]
name = "PR, Foz do Iguaçu"
codes = ["brprfi"]

[[sedes]]
name = "RS, Pelotas"
codes = ["brrspe"]

[[sedes]]
name = "RS, Passo Fundo"
codes = ["brrspf"]

[[sedes]]
name = "SC, Florianópolis"
codes = ["brscfl"]

[[sedes]]
name = "SC, Pinhalzinho"
codes = ["brscpi"]
