[package]
name = "membroadcast"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
tokio.workspace = true
tokio-stream.workspace = true
futures.workspace = true
