[titulo]
name = "Latin America"
codes = ["teambr", "teamca", "teamcb", "teammx", "teamno", "teamso"]

[[sedes]]
name = "Latin America"
codes = [""]

[[sedes]]
codes = ["teambrbr"]
name = "Brazil"

[[sedes]]
codes = ["teamca"]
name = "Central America"

[[sedes]]
name = "Caribe"
codes = ["teamcb"]

[[sedes]]
name = "Mexico"
codes = ["teammxmx"]

[[sedes]]
name = "South America - North"
codes = ["teamno"]

[[sedes]]
name = "South America - South"
codes = ["teamso"]
