[package]
name = "client-v2"
version = "2.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.8", features = ["csr"] }
leptos_router = { version = "0.8" }
gloo-timers = { version = "0", features = ["futures"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
data.workspace = true
itertools = "0"
leptos-use = { version = "0.19" }
codee = "0.3.0"
client-sdk.workspace = true
client-model.workspace = true
log.workspace = true
console_log.workspace = true
any_spawner = { version = "0.3", features = ["wasm-bindgen"] }

[dependencies.web-sys]
features = ["Window", "ScrollToOptions", "ScrollBehavior"]
version = "0"
