[package]
name = "server-v2"
version.workspace = true
edition.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "simples"
path = "src/main.rs"

[dependencies]
actix-files.workspace = true
actix-web.workspace = true
base64.workspace = true
actix-cors.workspace = true
actix-ws.workspace = true
tracing-actix-web.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
autometrics.workspace = true
thiserror.workspace = true
futures.workspace = true
tokio-stream.workspace = true
clap.workspace = true
color-eyre.workspace = true
tracing-subscriber.workspace = true
openssl-sys = { optional = true, version = "0.9" }

service.workspace = true
data.workspace = true
cli.workspace = true

[dev-dependencies]
actix-http = "3"

[features]
vendored = ["openssl-sys/vendored"]
